#! /usr/bin/env ruby

# An example of subcommands

require "clamp"

Clamp do

  option "--timeout", "SECONDS", "connection timeout", :default => 5, :environment_variable => "MYAPP_TIMEOUT" do |x|
    Integer(x)
  end

  parameter "HOST", "server address"
  parameter "[PORT]", "server port", :default => 80, :environment_variable => "MYAPP_PORT"

  def execute
    puts "trying to connect to #{host} on port #{port} (waiting up to #{timeout} seconds)"
  end

end
