#! /usr/bin/env ruby

# An example of multi-valued options

require "clamp"

Clamp do

  option ["-f", "--flavour"], "FLAVOUR", "flavour",
    :multivalued => true, :default => ['chocolate'],
    :attribute_name => :flavours

  def execute
    puts "one #{flavours.join(' and ')} ice-cream"
  end

end
