{
 "title": "Bloom-Compactor New",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "options": {
    "content": "## About the Bloom Compactor\nThe compactor iterates through chunks and creates blooms out of them.\nThe size of the resulting blooms depends on the bloom filter settings, the tokenizer settings, the number of ring tokens per compactor and the total number opf compactors.\n\nCompactors are horizontally scalable and uses a ring to:\n- Shard tenants\n- Shard series fingerprints within a tenant subring.\n\nThe blooms for the series are grouped together in blocks which are flushed to object store."
   }
  },
  {
   "title": "Progress",
   "type": "timeseries",
   "description": "Cell-wide compaction progress. Should increase till completion throughout each compaction period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(loki_bloomcompactor_progress{cluster=~\"$cluster\", job=~\"$namespace/bloom-compactor\"})\n/\nsum(count(loki_bloomcompactor_progress{cluster=~\"$cluster\", job=~\"$namespace/bloom-compactor\"}))",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(\n    0.9, \n    sum by (pod) (\n        loki_bloomcompactor_progress{cluster=~\"$cluster\", job=~\"$namespace/bloom-compactor\"}\n    )\n)",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(\n    0.1, \n    sum by (pod) (\n        loki_bloomcompactor_progress{cluster=~\"$cluster\", job=~\"$namespace/bloom-compactor\"}\n    )\n)",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Chunks and Bloom size",
   "type": "timeseries",
   "description": "Uncompressed size of chunks in a series VS the size of the blooms built.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(loki_bloom_size_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Bloom"
    },
    {
     "expr": "sum(rate(loki_bloomcompactor_chunk_series_size_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Chunk"
    },
    {
     "expr": "sum(rate(loki_bloom_size_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))\n/\nsum(rate(loki_bloomcompactor_chunk_series_size_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Ratio"
    },
    {
     "expr": "sum(rate(loki_bloom_size_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]))\n/\nsum(rate(loki_bloomcompactor_chunk_series_size_sum{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Ratio over range"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "description": "Blooms size vs uncompressed chunk size.",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} |= \"level=error\" |= \"component=bloom-compactor\""
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} |= \"level=error\" |= \"component=bloom-compactor\" [$__auto]))"
    }
   ]
  },
  {
   "title": "Progress per pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Progress per pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n    loki_bloomcompactor_progress{cluster=~\"$cluster\", job=~\"$namespace/bloom-compactor\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Progress per pod",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pod) (\n    loki_bloomcompactor_progress{cluster=~\"$cluster\", job=~\"$namespace/bloom-compactor\"}\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "We use tenant sharding so each compactor will process a subset of the tenants.",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
    },
    {
     "title": "Required CPUs to not lag behind",
     "type": "timeseries",
     "description": "Shows the expected number of cpu cores we need to provision to build blooms as fast as we ingest data so a compaction iteration doesn't take longer than the compaction interval.\n\nWe may decide to have more to speed up compaction.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "# This query shows the expected number of cpu cores we need to not fall behind\n# building blooms for data we're ingesting.\n# conceptually, the formula is:\n# (cell_bytes * space_amplification / bloom_bytes_processed_per_core)\n\n# number of replicas needed\nsum(avg_over_time(loki_cell:bytes:rate1m{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval]))\n*\n## Space amplification (how much data do we write compared to what we ingest?)\n(\n  # rep factor\n  3 *\n  sum(\n    # 1 - dedupe_ratio\n    1 - \n    sum(rate(loki_chunk_store_deduped_chunks_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (cluster, namespace)\n    /\n    sum(rate(loki_ingester_chunks_flushed_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (cluster, namespace)\n  )\n)\n/\n(\nsum(rate(loki_bloomcompactor_chunk_series_size_sum{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))\n/\nsum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))\n)",
       "legendFormat": "Needed"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "MB/s per core",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "# MB/s/core chunk data processed\nsum(rate(loki_bloomcompactor_chunk_series_size_sum{cluster=~\"$cluster\", job=~\"$namespace/bloom-compactor\"}[$__rate_interval]))\n/\nsum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\", resource=\"cpu\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\", resource=\"cpu\"} > 0)",
       "legendFormat": "Limit"
      },
      {
       "expr": "quantile(\n    0.99,\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"}[$__rate_interval])\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n    0.50,\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"}[$__rate_interval])\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "avg(\n    rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"}[$__rate_interval])\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "CPU per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\", resource=\"cpu\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\", resource=\"cpu\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"} > 0)",
       "legendFormat": "Limit"
      },
      {
       "expr": "quantile (\n  0.99,\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"}\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile (\n  0.50,\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"}\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "avg (\n  container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"}\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Memory per pod (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\", resource=\"memory\"} > 0)",
       "legendFormat": "Request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", container=~\"bloom-compactor\"} > 0)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (\n    increase(\n        kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[10m]\n    )\n) > 0",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "Container restarts reason per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(\n    sum by (pod) (\n        increase(\n            kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[10m]\n        )\n    )\n    * on (pod) group_right\n    max by (pod, reason) (\n        kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}\n    )\n) > 0",
       "legendFormat": "{{reason}} / {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloom building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tokens rate (millions)",
     "type": "timeseries",
     "description": "How many tokens each compactor is appending to blooms. Accounts for tokens that are not actually added to the blooms since they are already there. See the panel on the right for a drill down on the collision.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "# tokens checked per pod, millions/s\nsum(rate(loki_bloom_tokens_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))\n/\nsum(count(loki_bloom_tokens_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}))\n/ 1e6",
       "legendFormat": "Per core"
      },
      {
       "expr": "sum(rate(loki_bloom_inserts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])) / 1e6",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "tokens/s by collision type",
     "type": "timeseries",
     "description": "Collision type may be `false` (no collision), `cache` (found in token cache) or true (found in bloom filter).\n\nType may be either `raw` (the original ngram) or `chunk_prefixed` (the ngram with the chunk prefix)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "# tokens/s by type+collision\nsum by (collision) (\n    rate(loki_bloom_inserts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n) \n/ on () group_left\nsum (\n    rate(loki_bloom_inserts_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bloom size",
     "type": "timeseries",
     "description": "The sizes of the blooms created by the compactor. We build one bloom per series. The more unique ngrams and chunks the series has, the bigger their blooms will be.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99, \n    sum by (le) (\n        rate(loki_bloom_size_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.90, \n    sum by (le) (\n        rate(loki_bloom_size_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(\n    0.50, \n    sum by (le) (\n        rate(loki_bloom_size_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Chunks indexed",
     "type": "timeseries",
     "description": "How many chunks are we indexing in the blooms. Either:\n- `copied` from a pre-existing bloom block, or \n- `iterated` through all its entries if processed for the first time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "# chunks indexed, by iteration or copied from a pre-existing bloom\nsum(rate(loki_bloom_chunks_indexed_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])) by (type)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Created Blocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloomcompactor_blocks_created_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Deleted Blocks",
     "type": "timeseries",
     "description": "Compactors delete metas and blocks marked for deletion in the metas tombstones.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloomcompactor_blocks_deleted_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Blocks reused",
     "type": "timeseries",
     "description": "Number of overlapping bloom blocks reused when creating new blocks\n",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloomcompactor_blocks_reused_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "Blocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Metas building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Created Metas",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloomcompactor_metas_created_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "Metas"
      }
     ]
    },
    {
     "title": "Deleted Metas",
     "type": "timeseries",
     "description": "Compactors delete metas and blocks marked for deletion in the metas tombstones.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(loki_bloomcompactor_metas_deleted_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]))",
       "legendFormat": "Metas"
      }
     ]
    }
   ]
  },
  {
   "title": "Data processed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "We use tenant sharding so each compactor will process a subset of the tenants.",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
    },
    {
     "title": "Tenants",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "quantile(\n  0.99,\n  increase(\n    loki_bloomcompactor_tenants_started_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]\n  )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n  0.90,\n  increase(\n    loki_bloomcompactor_tenants_started_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]\n  )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "quantile(\n  0.50,\n  increase(\n    loki_bloomcompactor_tenants_started_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[30m]\n  )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Tenants per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
     "targets": [
      {
       "expr": "sum by (pod) (\n  increase(\n    loki_bloomcompactor_tenants_started_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of tenant tables processed. ",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 }
    },
    {
     "title": "Tenant Tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "quantile(\n  0.99,\n  increase(\n    loki_bloomcompactor_tenant_table_ranges_completed_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]\n  )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n  0.90,\n  increase(\n    loki_bloomcompactor_tenant_table_ranges_completed_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]\n  )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "quantile(\n  0.50,\n  increase(\n    loki_bloomcompactor_tenant_table_ranges_completed_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]\n  )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Tenant Tables per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "targets": [
      {
       "expr": "sum by (pod) (\n  increase(\n    loki_bloomcompactor_tenant_table_ranges_completed_total{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval]\n  )\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Series per compaction (includes series copied from other blocks)",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 }
    },
    {
     "title": "Series",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.99, \n    sum by (le) (\n        rate(loki_bloomcompactor_series_per_compaction_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.9, \n    sum by (le) (\n        rate(loki_bloomcompactor_series_per_compaction_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.5, \n    sum by (le) (\n        rate(loki_bloomcompactor_series_per_compaction_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "avg series per compaction by pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
     "targets": [
      {
       "expr": "sum by (pod) (\n    rate(loki_bloomcompactor_series_per_compaction_sum{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    /\n    rate(loki_bloomcompactor_series_per_compaction_count{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Number of bytes from chunks added to blocks during each compaction.",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 }
    },
    {
     "title": "Bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.99, \n    sum by (le) (\n        rate(loki_bloomcompactor_bytes_per_compaction_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.9, \n    sum by (le) (\n        rate(loki_bloomcompactor_bytes_per_compaction_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "# series checked per compaction\nhistogram_quantile(\n    0.5, \n    sum by (le) (\n        rate(loki_bloomcompactor_bytes_per_compaction_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "avg bytes per compaction by pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n    rate(loki_bloomcompactor_bytes_per_compaction_sum{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n    /\n    rate(loki_bloomcompactor_bytes_per_compaction_count{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"}[$__rate_interval])\n)",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 82 },
     "options": {
      "content": "\nCompactors write blocks to the attached PVs before flushing them into the object store.\nIt also download chunks and index files.\n\nAfter compacting a given tenant, all the downloaded index files and chunks, as well as the already flushed blocks are deleted."
     }
    },
    {
     "title": "Disk Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "quantile(\n    0.99,\n    max by(persistentvolumeclaim) (\n        kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} \n        / \n        kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n    ) \n    and \n    count by(persistentvolumeclaim) (\n        kube_persistentvolumeclaim_labels{cluster=~\"$cluster\", namespace=~\"$namespace\",label_name=~\"bloom-compactor\"}\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n    0.90,\n    max by(persistentvolumeclaim) (\n        kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} \n        / \n        kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n    ) \n    and \n    count by(persistentvolumeclaim) (\n        kube_persistentvolumeclaim_labels{cluster=~\"$cluster\", namespace=~\"$namespace\",label_name=~\"bloom-compactor\"}\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "quantile(\n    0.50,\n    max by(persistentvolumeclaim) (\n        kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} \n        / \n        kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}\n    ) \n    and \n    count by(persistentvolumeclaim) (\n        kube_persistentvolumeclaim_labels{cluster=~\"$cluster\", namespace=~\"$namespace\",label_name=~\"bloom-compactor\"}\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Disk Utilization per pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\"}) and count by(persistentvolumeclaim) (kube_persistentvolumeclaim_labels{cluster=~\"$cluster\", namespace=~\"$namespace\",label_name=~\"bloom-compactor\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "quantile(\n    0.99,\n    sum by(instance, pod, device) (\n        rate(node_disk_written_bytes_total[$__rate_interval])\n    ) \n    + ignoring(pod) group_right() \n    (\n        label_replace(\n            count by(instance, pod, device) (\n                container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}\n            ), \n            \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n        ) * 0\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n    0.90,\n    sum by(instance, pod, device) (\n        rate(node_disk_written_bytes_total[$__rate_interval])\n    ) \n    + ignoring(pod) group_right() \n    (\n        label_replace(\n            count by(instance, pod, device) (\n                container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}\n            ), \n            \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n        ) * 0\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "quantile(\n    0.50,\n    sum by(instance, pod, device) (\n        rate(node_disk_written_bytes_total[$__rate_interval])\n    ) \n    + ignoring(pod) group_right() \n    (\n        label_replace(\n            count by(instance, pod, device) (\n                container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}\n            ), \n            \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n        ) * 0\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Disk Writes per pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, device) (rate(node_disk_written_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "quantile(\n    0.99,\n    sum by(instance, pod, device) (\n        rate(node_disk_read_bytes_total[$__rate_interval])\n    ) + ignoring(pod) group_right()\n    (\n        label_replace(\n            count by(instance, pod, device) (\n                container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}\n            ), \n            \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n        ) * 0\n    )\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "quantile(\n    0.90,\n    sum by(instance, pod, device) (\n        rate(node_disk_read_bytes_total[$__rate_interval])\n    ) + ignoring(pod) group_right()\n    (\n        label_replace(\n            count by(instance, pod, device) (\n                container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}\n            ), \n            \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n        ) * 0\n    )\n)",
       "legendFormat": "p90"
      },
      {
       "expr": "quantile(\n    0.50,\n    sum by(instance, pod, device) (\n        rate(node_disk_read_bytes_total[$__rate_interval])\n    ) + ignoring(pod) group_right()\n    (\n        label_replace(\n            count by(instance, pod, device) (\n                container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}\n            ), \n            \"device\", \"$1\", \"device\", \"/dev/(.*)\"\n        ) * 0\n    )\n)",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Disk Reads per pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(instance, pod, device) (rate(node_disk_read_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", container=\"bloom-compactor\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 83 },
     "options": {
      "content": "Once all blocks and metas are built locally, the compactor flushes them to the object store.\n\nAfter each iteration, the compactor deletes the metas and blocks marked for deletion in the tombstones."
     }
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 86 }, "options": { "content": "---\n#### GCS\n" } },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(loki_gcs_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_gcs_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 93 }, "options": { "content": "---\n#### S3\n" } },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(loki_s3_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_s3_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 7, "w": 2, "x": 0, "y": 100 }, "options": { "content": "---\n#### Azure\nBlob Storage" } },
    {
     "title": "QPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 2, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (status_code, operation) (rate(loki_azure_blob_request_duration_seconds_count{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval]))",
       "legendFormat": "{{operation}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p99"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p90"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (operation, le) (rate(loki_azure_blob_request_duration_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", container=\"bloom-compactor\"} [$__rate_interval])))",
       "legendFormat": "{{operation}} p50"
      }
     ]
    }
   ]
  }
 ]
}