// Code generated by wiresmith. DO NOT EDIT.
// source: pkg/storage/chunk/cache/resultscache/test_types.proto

package resultscache

import (
	"math"
)

// Per-message Equal() methods for pkg/storage/chunk/cache/resultscache/test_types.proto.
//
// Equal is never called from Marshal / Unmarshal / Size on the hot path;
// emitting it next to those methods in the same compilation unit shifts
// the hot functions onto different cache lines / iTLB pages in the linked
// binary without buying anything for the (uncommon) Equal callers.
//
// Splitting Equal out into its own .o gives the linker freedom to place
// it away from the hot paths, mirroring the reflect/registration split
// documented in the companion _reflect.pb.go banner and in
// compiler/generator/emit_registration.go. DO NOT inline this file's
// contents back into the main .pb.go without re-measuring.

func (this *MockRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockRequest)
	if !ok {
		that2, ok := that.(MockRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Path != that1.Path {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	if this.Step != that1.Step {
		return false
	}
	if this.Query != that1.Query {
		return false
	}
	if !this.CachingOpts.Equal(that1.CachingOpts) {
		return false
	}
	return true
}

func (this *MockResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockResponse)
	if !ok {
		that2, ok := that.(MockResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for i := range this.Labels {
		if (this.Labels[i] == nil) != (that1.Labels[i] == nil) {
			return false
		}
		if this.Labels[i] != nil && !this.Labels[i].Equal(that1.Labels[i]) {
			return false
		}
	}
	if len(this.Samples) != len(that1.Samples) {
		return false
	}
	for i := range this.Samples {
		if (this.Samples[i] == nil) != (that1.Samples[i] == nil) {
			return false
		}
		if this.Samples[i] != nil && !this.Samples[i].Equal(that1.Samples[i]) {
			return false
		}
	}
	return true
}

func (this *MockLabelsPair) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockLabelsPair)
	if !ok {
		that2, ok := that.(MockLabelsPair)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}

func (this *MockSample) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MockSample)
	if !ok {
		that2, ok := that.(MockSample)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if math.Float64bits(this.Value) != math.Float64bits(that1.Value) {
		return false
	}
	if this.TimestampMs != that1.TimestampMs {
		return false
	}
	return true
}
