auth_enabled: true

querier:
  multi_tenant_queries_enabled: true

compactor:
  retention_enabled: false

server:
  http_listen_port: 3100

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_dev_005_tsdb_index_    # must match the original
        period: 24h

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

limits_config:
  allow_structured_metadata: false

ruler:
  alertmanager_url: http://localhost:9093
