apiVersion: 1
datasources:
  - access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    isDefault: true
    name: Loki
    type: loki
    uid: loki
    url: http://gateway:3100
    version: 1

  - access: proxy
    basicAuth: false
    editable: true
    isDefault: false
    name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    version: 1
