error_log  /dev/stderr;
pid        /tmp/nginx.pid;
worker_rlimit_nofile 8192;

events {
    worker_connections  4096;  ## Default: 1024
}

http {
  default_type application/octet-stream;
  access_log   /dev/stderr  combined;
  sendfile     on;
  tcp_nopush   on;

  upstream loki {
    server loki-monolithic:3100;
    server loki-monolithic-compactor:3100;
  }

  upstream compactor {
    server loki-monolithic-compactor:3100;
  }

  server {
    # listen 80;
    listen 3100;

    location / {
        proxy_pass       http://loki;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /loki/api/v1/tail {
        proxy_pass       http://loki;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection       "upgrade";
    }

    ## Route delete requests to the `main` compactor instance
    location ~ ^/loki/api/v1/delete {
        proxy_pass       http://compactor;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
