// Code generated by wiresmith. DO NOT EDIT.
// source: pkg/logqlmodel/stats/stats.proto

package stats

import (
	"math"
)

// Per-message Compare() methods for pkg/logqlmodel/stats/stats.proto.
//
// Compare returns -1/0/+1 like bytes.Compare with the gogoproto.compare
// nil/wrong-type preamble. Always emitted on every message; callers that
// don't use it can rely on Go's dead-code elimination to drop the body.
//
// Why a separate file? Compare is never called from Marshal/Unmarshal/Size,
// but emitting it next to those hot functions in the main .pb.go pushed
// them onto different cache sets and produced a measured ~9% geomean
// regression on OTel benchmarks (UnmarshalMap +14%, MarshalSingleSpan +13%)
// purely from icache / iTLB / BTB pressure. Splitting Compare into its own
// compilation unit gives the linker freedom to place the cold half away
// from the hot half — same trick the _reflect.pb.go split uses.
//
// See compiler/generator/emit_compare.go for the full rationale and the
// benchmark methodology. DO NOT inline this file's contents back into
// the main .pb.go without re-measuring.

func (this *Result) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Result)
	if !ok {
		that2, ok := that.(Result)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := this.Summary.Compare(that1.Summary); c != 0 {
		return c
	}
	if c := this.Querier.Compare(that1.Querier); c != 0 {
		return c
	}
	if c := this.Ingester.Compare(that1.Ingester); c != 0 {
		return c
	}
	if c := this.Caches.Compare(that1.Caches); c != 0 {
		return c
	}
	if c := this.Index.Compare(that1.Index); c != 0 {
		return c
	}
	return 0
}

func (this *Caches) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Caches)
	if !ok {
		that2, ok := that.(Caches)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := this.Chunk.Compare(that1.Chunk); c != 0 {
		return c
	}
	if c := this.Index.Compare(that1.Index); c != 0 {
		return c
	}
	if c := this.Result.Compare(that1.Result); c != 0 {
		return c
	}
	if c := this.StatsResult.Compare(that1.StatsResult); c != 0 {
		return c
	}
	if c := this.VolumeResult.Compare(that1.VolumeResult); c != 0 {
		return c
	}
	if c := this.SeriesResult.Compare(that1.SeriesResult); c != 0 {
		return c
	}
	if c := this.LabelResult.Compare(that1.LabelResult); c != 0 {
		return c
	}
	if c := this.InstantMetricResult.Compare(that1.InstantMetricResult); c != 0 {
		return c
	}
	if c := this.LogResult.Compare(that1.LogResult); c != 0 {
		return c
	}
	if c := this.TaskResult.Compare(that1.TaskResult); c != 0 {
		return c
	}
	return 0
}

func (this *Summary) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Summary)
	if !ok {
		that2, ok := that.(Summary)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.BytesProcessedPerSecond != that1.BytesProcessedPerSecond {
		if this.BytesProcessedPerSecond < that1.BytesProcessedPerSecond {
			return -1
		}
		return 1
	}
	if this.LinesProcessedPerSecond != that1.LinesProcessedPerSecond {
		if this.LinesProcessedPerSecond < that1.LinesProcessedPerSecond {
			return -1
		}
		return 1
	}
	if this.TotalBytesProcessed != that1.TotalBytesProcessed {
		if this.TotalBytesProcessed < that1.TotalBytesProcessed {
			return -1
		}
		return 1
	}
	if this.TotalLinesProcessed != that1.TotalLinesProcessed {
		if this.TotalLinesProcessed < that1.TotalLinesProcessed {
			return -1
		}
		return 1
	}
	if math.Float64bits(this.ExecTime) != math.Float64bits(that1.ExecTime) {
		if math.Float64bits(this.ExecTime) < math.Float64bits(that1.ExecTime) {
			return -1
		}
		return 1
	}
	if math.Float64bits(this.QueueTime) != math.Float64bits(that1.QueueTime) {
		if math.Float64bits(this.QueueTime) < math.Float64bits(that1.QueueTime) {
			return -1
		}
		return 1
	}
	if this.Subqueries != that1.Subqueries {
		if this.Subqueries < that1.Subqueries {
			return -1
		}
		return 1
	}
	if this.TotalEntriesReturned != that1.TotalEntriesReturned {
		if this.TotalEntriesReturned < that1.TotalEntriesReturned {
			return -1
		}
		return 1
	}
	if this.Splits != that1.Splits {
		if this.Splits < that1.Splits {
			return -1
		}
		return 1
	}
	if this.Shards != that1.Shards {
		if this.Shards < that1.Shards {
			return -1
		}
		return 1
	}
	if this.TotalPostFilterLines != that1.TotalPostFilterLines {
		if this.TotalPostFilterLines < that1.TotalPostFilterLines {
			return -1
		}
		return 1
	}
	if this.TotalStructuredMetadataBytesProcessed != that1.TotalStructuredMetadataBytesProcessed {
		if this.TotalStructuredMetadataBytesProcessed < that1.TotalStructuredMetadataBytesProcessed {
			return -1
		}
		return 1
	}
	if this.EstimatedQueryBytes != that1.EstimatedQueryBytes {
		if this.EstimatedQueryBytes < that1.EstimatedQueryBytes {
			return -1
		}
		return 1
	}
	return 0
}

func (this *Index) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Index)
	if !ok {
		that2, ok := that.(Index)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.TotalChunks != that1.TotalChunks {
		if this.TotalChunks < that1.TotalChunks {
			return -1
		}
		return 1
	}
	if this.PostFilterChunks != that1.PostFilterChunks {
		if this.PostFilterChunks < that1.PostFilterChunks {
			return -1
		}
		return 1
	}
	if this.ShardsDuration != that1.ShardsDuration {
		if this.ShardsDuration < that1.ShardsDuration {
			return -1
		}
		return 1
	}
	if this.UsedBloomFilters != that1.UsedBloomFilters {
		if !this.UsedBloomFilters && that1.UsedBloomFilters {
			return -1
		}
		return 1
	}
	if this.TotalStreams != that1.TotalStreams {
		if this.TotalStreams < that1.TotalStreams {
			return -1
		}
		return 1
	}
	if math.Float64bits(this.ChunkRefsLookupTime) != math.Float64bits(that1.ChunkRefsLookupTime) {
		if math.Float64bits(this.ChunkRefsLookupTime) < math.Float64bits(that1.ChunkRefsLookupTime) {
			return -1
		}
		return 1
	}
	if math.Float64bits(this.BloomFilterTime) != math.Float64bits(that1.BloomFilterTime) {
		if math.Float64bits(this.BloomFilterTime) < math.Float64bits(that1.BloomFilterTime) {
			return -1
		}
		return 1
	}
	return 0
}

func (this *Querier) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Querier)
	if !ok {
		that2, ok := that.(Querier)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := this.Store.Compare(that1.Store); c != 0 {
		return c
	}
	if math.Float64bits(this.QuerierExecTime) != math.Float64bits(that1.QuerierExecTime) {
		if math.Float64bits(this.QuerierExecTime) < math.Float64bits(that1.QuerierExecTime) {
			return -1
		}
		return 1
	}
	return 0
}

func (this *Ingester) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Ingester)
	if !ok {
		that2, ok := that.(Ingester)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.TotalReached != that1.TotalReached {
		if this.TotalReached < that1.TotalReached {
			return -1
		}
		return 1
	}
	if this.TotalChunksMatched != that1.TotalChunksMatched {
		if this.TotalChunksMatched < that1.TotalChunksMatched {
			return -1
		}
		return 1
	}
	if this.TotalBatches != that1.TotalBatches {
		if this.TotalBatches < that1.TotalBatches {
			return -1
		}
		return 1
	}
	if this.TotalLinesSent != that1.TotalLinesSent {
		if this.TotalLinesSent < that1.TotalLinesSent {
			return -1
		}
		return 1
	}
	if c := this.Store.Compare(that1.Store); c != 0 {
		return c
	}
	if math.Float64bits(this.RecvWaitTime) != math.Float64bits(that1.RecvWaitTime) {
		if math.Float64bits(this.RecvWaitTime) < math.Float64bits(that1.RecvWaitTime) {
			return -1
		}
		return 1
	}
	return 0
}

func (this *Store) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Store)
	if !ok {
		that2, ok := that.(Store)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.TotalChunksRef != that1.TotalChunksRef {
		if this.TotalChunksRef < that1.TotalChunksRef {
			return -1
		}
		return 1
	}
	if this.TotalChunksDownloaded != that1.TotalChunksDownloaded {
		if this.TotalChunksDownloaded < that1.TotalChunksDownloaded {
			return -1
		}
		return 1
	}
	if this.ChunksDownloadTime != that1.ChunksDownloadTime {
		if this.ChunksDownloadTime < that1.ChunksDownloadTime {
			return -1
		}
		return 1
	}
	if c := this.Chunk.Compare(that1.Chunk); c != 0 {
		return c
	}
	if this.ChunkRefsFetchTime != that1.ChunkRefsFetchTime {
		if this.ChunkRefsFetchTime < that1.ChunkRefsFetchTime {
			return -1
		}
		return 1
	}
	if this.CongestionControlLatency != that1.CongestionControlLatency {
		if this.CongestionControlLatency < that1.CongestionControlLatency {
			return -1
		}
		return 1
	}
	if this.PipelineWrapperFilteredLines != that1.PipelineWrapperFilteredLines {
		if this.PipelineWrapperFilteredLines < that1.PipelineWrapperFilteredLines {
			return -1
		}
		return 1
	}
	if c := this.Dataobj.Compare(that1.Dataobj); c != 0 {
		return c
	}
	if this.QueryReferencedStructured != that1.QueryReferencedStructured {
		if !this.QueryReferencedStructured && that1.QueryReferencedStructured {
			return -1
		}
		return 1
	}
	if this.QueryUsedV2Engine != that1.QueryUsedV2Engine {
		if !this.QueryUsedV2Engine && that1.QueryUsedV2Engine {
			return -1
		}
		return 1
	}
	return 0
}

func (this *Dataobj) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Dataobj)
	if !ok {
		that2, ok := that.(Dataobj)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.PrePredicateDecompressedRows != that1.PrePredicateDecompressedRows {
		if this.PrePredicateDecompressedRows < that1.PrePredicateDecompressedRows {
			return -1
		}
		return 1
	}
	if this.PrePredicateDecompressedBytes != that1.PrePredicateDecompressedBytes {
		if this.PrePredicateDecompressedBytes < that1.PrePredicateDecompressedBytes {
			return -1
		}
		return 1
	}
	if this.PrePredicateDecompressedStructuredMetadataBytes != that1.PrePredicateDecompressedStructuredMetadataBytes {
		if this.PrePredicateDecompressedStructuredMetadataBytes < that1.PrePredicateDecompressedStructuredMetadataBytes {
			return -1
		}
		return 1
	}
	if this.PostPredicateRows != that1.PostPredicateRows {
		if this.PostPredicateRows < that1.PostPredicateRows {
			return -1
		}
		return 1
	}
	if this.PostPredicateDecompressedBytes != that1.PostPredicateDecompressedBytes {
		if this.PostPredicateDecompressedBytes < that1.PostPredicateDecompressedBytes {
			return -1
		}
		return 1
	}
	if this.PostPredicateStructuredMetadataBytes != that1.PostPredicateStructuredMetadataBytes {
		if this.PostPredicateStructuredMetadataBytes < that1.PostPredicateStructuredMetadataBytes {
			return -1
		}
		return 1
	}
	if this.PostFilterRows != that1.PostFilterRows {
		if this.PostFilterRows < that1.PostFilterRows {
			return -1
		}
		return 1
	}
	if this.PagesScanned != that1.PagesScanned {
		if this.PagesScanned < that1.PagesScanned {
			return -1
		}
		return 1
	}
	if this.PagesDownloaded != that1.PagesDownloaded {
		if this.PagesDownloaded < that1.PagesDownloaded {
			return -1
		}
		return 1
	}
	if this.PagesDownloadedBytes != that1.PagesDownloadedBytes {
		if this.PagesDownloadedBytes < that1.PagesDownloadedBytes {
			return -1
		}
		return 1
	}
	if this.PageBatches != that1.PageBatches {
		if this.PageBatches < that1.PageBatches {
			return -1
		}
		return 1
	}
	if this.TotalRowsAvailable != that1.TotalRowsAvailable {
		if this.TotalRowsAvailable < that1.TotalRowsAvailable {
			return -1
		}
		return 1
	}
	if this.TotalPageDownloadTime != that1.TotalPageDownloadTime {
		if this.TotalPageDownloadTime < that1.TotalPageDownloadTime {
			return -1
		}
		return 1
	}
	if this.WireBytesTransferred != that1.WireBytesTransferred {
		if this.WireBytesTransferred < that1.WireBytesTransferred {
			return -1
		}
		return 1
	}
	return 0
}

func (this *Chunk) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Chunk)
	if !ok {
		that2, ok := that.(Chunk)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.HeadChunkBytes != that1.HeadChunkBytes {
		if this.HeadChunkBytes < that1.HeadChunkBytes {
			return -1
		}
		return 1
	}
	if this.HeadChunkLines != that1.HeadChunkLines {
		if this.HeadChunkLines < that1.HeadChunkLines {
			return -1
		}
		return 1
	}
	if this.DecompressedBytes != that1.DecompressedBytes {
		if this.DecompressedBytes < that1.DecompressedBytes {
			return -1
		}
		return 1
	}
	if this.DecompressedLines != that1.DecompressedLines {
		if this.DecompressedLines < that1.DecompressedLines {
			return -1
		}
		return 1
	}
	if this.CompressedBytes != that1.CompressedBytes {
		if this.CompressedBytes < that1.CompressedBytes {
			return -1
		}
		return 1
	}
	if this.TotalDuplicates != that1.TotalDuplicates {
		if this.TotalDuplicates < that1.TotalDuplicates {
			return -1
		}
		return 1
	}
	if this.PostFilterLines != that1.PostFilterLines {
		if this.PostFilterLines < that1.PostFilterLines {
			return -1
		}
		return 1
	}
	if this.HeadChunkStructuredMetadataBytes != that1.HeadChunkStructuredMetadataBytes {
		if this.HeadChunkStructuredMetadataBytes < that1.HeadChunkStructuredMetadataBytes {
			return -1
		}
		return 1
	}
	if this.DecompressedStructuredMetadataBytes != that1.DecompressedStructuredMetadataBytes {
		if this.DecompressedStructuredMetadataBytes < that1.DecompressedStructuredMetadataBytes {
			return -1
		}
		return 1
	}
	return 0
}

func (this *Cache) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Cache)
	if !ok {
		that2, ok := that.(Cache)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.EntriesFound != that1.EntriesFound {
		if this.EntriesFound < that1.EntriesFound {
			return -1
		}
		return 1
	}
	if this.EntriesRequested != that1.EntriesRequested {
		if this.EntriesRequested < that1.EntriesRequested {
			return -1
		}
		return 1
	}
	if this.EntriesStored != that1.EntriesStored {
		if this.EntriesStored < that1.EntriesStored {
			return -1
		}
		return 1
	}
	if this.BytesReceived != that1.BytesReceived {
		if this.BytesReceived < that1.BytesReceived {
			return -1
		}
		return 1
	}
	if this.BytesSent != that1.BytesSent {
		if this.BytesSent < that1.BytesSent {
			return -1
		}
		return 1
	}
	if this.Requests != that1.Requests {
		if this.Requests < that1.Requests {
			return -1
		}
		return 1
	}
	if this.DownloadTime != that1.DownloadTime {
		if this.DownloadTime < that1.DownloadTime {
			return -1
		}
		return 1
	}
	if this.QueryLengthServed != that1.QueryLengthServed {
		if this.QueryLengthServed < that1.QueryLengthServed {
			return -1
		}
		return 1
	}
	return 0
}
