{{- $isDistributed := eq (include "loki.deployment.isDistributed" .Subcharts.loki) "true" -}}
{{- if and $isDistributed (gt (int .Values.patternIngester.replicas) 0) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.patternIngesterFullname" .Subcharts.loki }}-headless
  namespace: {{ include "loki.namespace" .Subcharts.loki }}
  labels:
    {{- include "loki.patternIngesterLabels" .Subcharts.loki | nindent 4 }}
  {{- with .Values.loki.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "loki.patternIngesterSelectorLabels" .Subcharts.loki | nindent 4 }}
{{- end -}}
