// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: pkg/logproto/bloomgateway.proto

package logproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BloomGateway_FilterChunkRefs_FullMethodName     = "/logproto.BloomGateway/FilterChunkRefs"
	BloomGateway_PrefetchBloomBlocks_FullMethodName = "/logproto.BloomGateway/PrefetchBloomBlocks"
)

// BloomGatewayClient is the client API for BloomGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BloomGatewayClient interface {
	FilterChunkRefs(ctx context.Context, in *FilterChunkRefRequest, opts ...grpc.CallOption) (*FilterChunkRefResponse, error)
	PrefetchBloomBlocks(ctx context.Context, in *PrefetchBloomBlocksRequest, opts ...grpc.CallOption) (*PrefetchBloomBlocksResponse, error)
}

type bloomGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewBloomGatewayClient(cc grpc.ClientConnInterface) BloomGatewayClient {
	return &bloomGatewayClient{cc}
}

func (c *bloomGatewayClient) FilterChunkRefs(ctx context.Context, in *FilterChunkRefRequest, opts ...grpc.CallOption) (*FilterChunkRefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterChunkRefResponse)
	err := c.cc.Invoke(ctx, BloomGateway_FilterChunkRefs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloomGatewayClient) PrefetchBloomBlocks(ctx context.Context, in *PrefetchBloomBlocksRequest, opts ...grpc.CallOption) (*PrefetchBloomBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefetchBloomBlocksResponse)
	err := c.cc.Invoke(ctx, BloomGateway_PrefetchBloomBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BloomGatewayServer is the server API for BloomGateway service.
// All implementations must embed UnimplementedBloomGatewayServer
// for forward compatibility.
type BloomGatewayServer interface {
	FilterChunkRefs(context.Context, *FilterChunkRefRequest) (*FilterChunkRefResponse, error)
	PrefetchBloomBlocks(context.Context, *PrefetchBloomBlocksRequest) (*PrefetchBloomBlocksResponse, error)
	mustEmbedUnimplementedBloomGatewayServer()
}

// UnimplementedBloomGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBloomGatewayServer struct{}

func (UnimplementedBloomGatewayServer) FilterChunkRefs(context.Context, *FilterChunkRefRequest) (*FilterChunkRefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FilterChunkRefs not implemented")
}
func (UnimplementedBloomGatewayServer) PrefetchBloomBlocks(context.Context, *PrefetchBloomBlocksRequest) (*PrefetchBloomBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrefetchBloomBlocks not implemented")
}
func (UnimplementedBloomGatewayServer) mustEmbedUnimplementedBloomGatewayServer() {}
func (UnimplementedBloomGatewayServer) testEmbeddedByValue()                      {}

// UnsafeBloomGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BloomGatewayServer will
// result in compilation errors.
type UnsafeBloomGatewayServer interface {
	mustEmbedUnimplementedBloomGatewayServer()
}

func RegisterBloomGatewayServer(s grpc.ServiceRegistrar, srv BloomGatewayServer) {
	// If the following call panics, it indicates UnimplementedBloomGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BloomGateway_ServiceDesc, srv)
}

func _BloomGateway_FilterChunkRefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterChunkRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomGatewayServer).FilterChunkRefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomGateway_FilterChunkRefs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomGatewayServer).FilterChunkRefs(ctx, req.(*FilterChunkRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloomGateway_PrefetchBloomBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrefetchBloomBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomGatewayServer).PrefetchBloomBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomGateway_PrefetchBloomBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomGatewayServer).PrefetchBloomBlocks(ctx, req.(*PrefetchBloomBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BloomGateway_ServiceDesc is the grpc.ServiceDesc for BloomGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BloomGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logproto.BloomGateway",
	HandlerType: (*BloomGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FilterChunkRefs",
			Handler:    _BloomGateway_FilterChunkRefs_Handler,
		},
		{
			MethodName: "PrefetchBloomBlocks",
			Handler:    _BloomGateway_PrefetchBloomBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/logproto/bloomgateway.proto",
}
