// Code generated by wiresmith. DO NOT EDIT.
// source: pkg/logproto/logproto.proto

package logproto

import (
	"bytes"
	"math"
)

// Per-message Equal() methods for pkg/logproto/logproto.proto.
//
// Equal is never called from Marshal / Unmarshal / Size on the hot path;
// emitting it next to those methods in the same compilation unit shifts
// the hot functions onto different cache lines / iTLB pages in the linked
// binary without buying anything for the (uncommon) Equal callers.
//
// Splitting Equal out into its own .o gives the linker freedom to place
// it away from the hot paths, mirroring the reflect/registration split
// documented in the companion _reflect.pb.go banner and in
// compiler/generator/emit_registration.go. DO NOT inline this file's
// contents back into the main .pb.go without re-measuring.

func (this *LabelToValuesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LabelToValuesResponse)
	if !ok {
		that2, ok := that.(LabelToValuesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for k, v := range this.Labels {
		v2, ok := that1.Labels[k]
		if !ok {
			return false
		}
		if !v.Equal(v2) {
			return false
		}
	}
	return true
}

func (this *UniqueLabelValues) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UniqueLabelValues)
	if !ok {
		that2, ok := that.(UniqueLabelValues)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Values) != len(that1.Values) {
		return false
	}
	for i := range this.Values {
		if this.Values[i] != that1.Values[i] {
			return false
		}
	}
	return true
}

func (this *StreamRatesRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StreamRatesRequest)
	if !ok {
		that2, ok := that.(StreamRatesRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}

func (this *StreamRatesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StreamRatesResponse)
	if !ok {
		that2, ok := that.(StreamRatesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.StreamRates) != len(that1.StreamRates) {
		return false
	}
	for i := range this.StreamRates {
		if (this.StreamRates[i] == nil) != (that1.StreamRates[i] == nil) {
			return false
		}
		if this.StreamRates[i] != nil && !this.StreamRates[i].Equal(that1.StreamRates[i]) {
			return false
		}
	}
	return true
}

func (this *StreamRate) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*StreamRate)
	if !ok {
		that2, ok := that.(StreamRate)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StreamHash != that1.StreamHash {
		return false
	}
	if this.StreamHashNoShard != that1.StreamHashNoShard {
		return false
	}
	if this.Rate != that1.Rate {
		return false
	}
	if this.Tenant != that1.Tenant {
		return false
	}
	if this.Pushes != that1.Pushes {
		return false
	}
	return true
}

func (this *QueryRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryRequest)
	if !ok {
		that2, ok := that.(QueryRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Selector != that1.Selector {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	if this.Direction != that1.Direction {
		return false
	}
	if len(this.Shards) != len(that1.Shards) {
		return false
	}
	for i := range this.Shards {
		if this.Shards[i] != that1.Shards[i] {
			return false
		}
	}
	if len(this.Deletes) != len(that1.Deletes) {
		return false
	}
	for i := range this.Deletes {
		if (this.Deletes[i] == nil) != (that1.Deletes[i] == nil) {
			return false
		}
		if this.Deletes[i] != nil && !this.Deletes[i].Equal(that1.Deletes[i]) {
			return false
		}
	}
	if !this.Plan.EqualWiresmith(that1.Plan) {
		return false
	}
	if (this.StoreChunks == nil) != (that1.StoreChunks == nil) {
		return false
	}
	if this.StoreChunks != nil && !this.StoreChunks.Equal(that1.StoreChunks) {
		return false
	}
	return true
}

func (this *SampleQueryRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleQueryRequest)
	if !ok {
		that2, ok := that.(SampleQueryRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Selector != that1.Selector {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	if len(this.Shards) != len(that1.Shards) {
		return false
	}
	for i := range this.Shards {
		if this.Shards[i] != that1.Shards[i] {
			return false
		}
	}
	if len(this.Deletes) != len(that1.Deletes) {
		return false
	}
	for i := range this.Deletes {
		if (this.Deletes[i] == nil) != (that1.Deletes[i] == nil) {
			return false
		}
		if this.Deletes[i] != nil && !this.Deletes[i].Equal(that1.Deletes[i]) {
			return false
		}
	}
	if !this.Plan.EqualWiresmith(that1.Plan) {
		return false
	}
	if (this.StoreChunks == nil) != (that1.StoreChunks == nil) {
		return false
	}
	if this.StoreChunks != nil && !this.StoreChunks.Equal(that1.StoreChunks) {
		return false
	}
	return true
}

func (this *Plan) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Plan)
	if !ok {
		that2, ok := that.(Plan)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Raw, that1.Raw) {
		return false
	}
	return true
}

func (this *Delete) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Delete)
	if !ok {
		that2, ok := that.(Delete)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Selector != that1.Selector {
		return false
	}
	if this.Start != that1.Start {
		return false
	}
	if this.End != that1.End {
		return false
	}
	return true
}

func (this *QueryResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryResponse)
	if !ok {
		that2, ok := that.(QueryResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Streams) != len(that1.Streams) {
		return false
	}
	for i := range this.Streams {
		if !this.Streams[i].EqualWiresmith(that1.Streams[i]) {
			return false
		}
	}
	if !this.Stats.Equal(that1.Stats) {
		return false
	}
	if len(this.Warnings) != len(that1.Warnings) {
		return false
	}
	for i := range this.Warnings {
		if this.Warnings[i] != that1.Warnings[i] {
			return false
		}
	}
	return true
}

func (this *SampleQueryResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleQueryResponse)
	if !ok {
		that2, ok := that.(SampleQueryResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Series) != len(that1.Series) {
		return false
	}
	for i := range this.Series {
		if !this.Series[i].Equal(that1.Series[i]) {
			return false
		}
	}
	if !this.Stats.Equal(that1.Stats) {
		return false
	}
	if len(this.Warnings) != len(that1.Warnings) {
		return false
	}
	for i := range this.Warnings {
		if this.Warnings[i] != that1.Warnings[i] {
			return false
		}
	}
	return true
}

func (this *LabelRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LabelRequest)
	if !ok {
		that2, ok := that.(LabelRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Values != that1.Values {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	if this.Query != that1.Query {
		return false
	}
	return true
}

func (this *LabelResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LabelResponse)
	if !ok {
		that2, ok := that.(LabelResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Values) != len(that1.Values) {
		return false
	}
	for i := range this.Values {
		if this.Values[i] != that1.Values[i] {
			return false
		}
	}
	return true
}

func (this *Sample) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Sample)
	if !ok {
		that2, ok := that.(Sample)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if math.Float64bits(this.Value) != math.Float64bits(that1.Value) {
		return false
	}
	if this.Hash != that1.Hash {
		return false
	}
	return true
}

func (this *LegacySample) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LegacySample)
	if !ok {
		that2, ok := that.(LegacySample)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if math.Float64bits(this.Value) != math.Float64bits(that1.Value) {
		return false
	}
	if this.TimestampMs != that1.TimestampMs {
		return false
	}
	return true
}

func (this *Series) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Series)
	if !ok {
		that2, ok := that.(Series)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Labels != that1.Labels {
		return false
	}
	if len(this.Samples) != len(that1.Samples) {
		return false
	}
	for i := range this.Samples {
		if !this.Samples[i].Equal(that1.Samples[i]) {
			return false
		}
	}
	if this.StreamHash != that1.StreamHash {
		return false
	}
	return true
}

func (this *TailRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TailRequest)
	if !ok {
		that2, ok := that.(TailRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Query != that1.Query {
		return false
	}
	if this.DelayFor != that1.DelayFor {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.Plan.EqualWiresmith(that1.Plan) {
		return false
	}
	return true
}

func (this *TailResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TailResponse)
	if !ok {
		that2, ok := that.(TailResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Stream.EqualWiresmith(that1.Stream) {
		return false
	}
	if len(this.DroppedStreams) != len(that1.DroppedStreams) {
		return false
	}
	for i := range this.DroppedStreams {
		if (this.DroppedStreams[i] == nil) != (that1.DroppedStreams[i] == nil) {
			return false
		}
		if this.DroppedStreams[i] != nil && !this.DroppedStreams[i].Equal(that1.DroppedStreams[i]) {
			return false
		}
	}
	return true
}

func (this *SeriesRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SeriesRequest)
	if !ok {
		that2, ok := that.(SeriesRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	if len(this.Groups) != len(that1.Groups) {
		return false
	}
	for i := range this.Groups {
		if this.Groups[i] != that1.Groups[i] {
			return false
		}
	}
	if len(this.Shards) != len(that1.Shards) {
		return false
	}
	for i := range this.Shards {
		if this.Shards[i] != that1.Shards[i] {
			return false
		}
	}
	return true
}

func (this *SeriesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SeriesResponse)
	if !ok {
		that2, ok := that.(SeriesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Series) != len(that1.Series) {
		return false
	}
	for i := range this.Series {
		if !this.Series[i].Equal(that1.Series[i]) {
			return false
		}
	}
	return true
}

func (this *SeriesIdentifier_LabelsEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SeriesIdentifier_LabelsEntry)
	if !ok {
		that2, ok := that.(SeriesIdentifier_LabelsEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Key != that1.Key {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}

func (this *SeriesIdentifier) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SeriesIdentifier)
	if !ok {
		that2, ok := that.(SeriesIdentifier)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for i := range this.Labels {
		if !this.Labels[i].Equal(that1.Labels[i]) {
			return false
		}
	}
	return true
}

func (this *DroppedStream) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DroppedStream)
	if !ok {
		that2, ok := that.(DroppedStream)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.From.Equal(that1.From) {
		return false
	}
	if !this.To.Equal(that1.To) {
		return false
	}
	if this.Labels != that1.Labels {
		return false
	}
	return true
}

func (this *LabelPair) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LabelPair)
	if !ok {
		that2, ok := that.(LabelPair)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}

func (this *LegacyLabelPair) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LegacyLabelPair)
	if !ok {
		that2, ok := that.(LegacyLabelPair)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Name, that1.Name) {
		return false
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return false
	}
	return true
}

func (this *Chunk) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Chunk)
	if !ok {
		that2, ok := that.(Chunk)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	return true
}

func (this *TailersCountRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TailersCountRequest)
	if !ok {
		that2, ok := that.(TailersCountRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}

func (this *TailersCountResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TailersCountResponse)
	if !ok {
		that2, ok := that.(TailersCountResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	return true
}

func (this *GetChunkIDsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetChunkIDsRequest)
	if !ok {
		that2, ok := that.(GetChunkIDsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Matchers != that1.Matchers {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	return true
}

func (this *GetChunkIDsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetChunkIDsResponse)
	if !ok {
		that2, ok := that.(GetChunkIDsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.ChunkIDs) != len(that1.ChunkIDs) {
		return false
	}
	for i := range this.ChunkIDs {
		if this.ChunkIDs[i] != that1.ChunkIDs[i] {
			return false
		}
	}
	return true
}

func (this *ChunkRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ChunkRef)
	if !ok {
		that2, ok := that.(ChunkRef)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Fingerprint != that1.Fingerprint {
		return false
	}
	if this.UserID != that1.UserID {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.Through != that1.Through {
		return false
	}
	if this.Checksum != that1.Checksum {
		return false
	}
	return true
}

func (this *ChunkRefGroup) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ChunkRefGroup)
	if !ok {
		that2, ok := that.(ChunkRefGroup)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Refs) != len(that1.Refs) {
		return false
	}
	for i := range this.Refs {
		if (this.Refs[i] == nil) != (that1.Refs[i] == nil) {
			return false
		}
		if this.Refs[i] != nil && !this.Refs[i].Equal(that1.Refs[i]) {
			return false
		}
	}
	return true
}

func (this *LabelValuesForMetricNameRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LabelValuesForMetricNameRequest)
	if !ok {
		that2, ok := that.(LabelValuesForMetricNameRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MetricName != that1.MetricName {
		return false
	}
	if this.LabelName != that1.LabelName {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.Through != that1.Through {
		return false
	}
	if this.Matchers != that1.Matchers {
		return false
	}
	return true
}

func (this *LabelNamesForMetricNameRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LabelNamesForMetricNameRequest)
	if !ok {
		that2, ok := that.(LabelNamesForMetricNameRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MetricName != that1.MetricName {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.Through != that1.Through {
		return false
	}
	if this.Matchers != that1.Matchers {
		return false
	}
	return true
}

func (this *LineFilter) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LineFilter)
	if !ok {
		that2, ok := that.(LineFilter)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Raw, that1.Raw) {
		return false
	}
	return true
}

func (this *GetChunkRefRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetChunkRefRequest)
	if !ok {
		that2, ok := that.(GetChunkRefRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.Through != that1.Through {
		return false
	}
	if this.Matchers != that1.Matchers {
		return false
	}
	if len(this.Filters) != len(that1.Filters) {
		return false
	}
	for i := range this.Filters {
		if !this.Filters[i].EqualWiresmith(that1.Filters[i]) {
			return false
		}
	}
	if !this.Plan.EqualWiresmith(that1.Plan) {
		return false
	}
	return true
}

func (this *GetChunkRefResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetChunkRefResponse)
	if !ok {
		that2, ok := that.(GetChunkRefResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Refs) != len(that1.Refs) {
		return false
	}
	for i := range this.Refs {
		if (this.Refs[i] == nil) != (that1.Refs[i] == nil) {
			return false
		}
		if this.Refs[i] != nil && !this.Refs[i].Equal(that1.Refs[i]) {
			return false
		}
	}
	if !this.Stats.Equal(that1.Stats) {
		return false
	}
	return true
}

func (this *GetSeriesRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSeriesRequest)
	if !ok {
		that2, ok := that.(GetSeriesRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.Through != that1.Through {
		return false
	}
	if this.Matchers != that1.Matchers {
		return false
	}
	return true
}

func (this *GetSeriesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetSeriesResponse)
	if !ok {
		that2, ok := that.(GetSeriesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Series) != len(that1.Series) {
		return false
	}
	for i := range this.Series {
		if !this.Series[i].Equal(that1.Series[i]) {
			return false
		}
	}
	return true
}

func (this *IndexSeries) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*IndexSeries)
	if !ok {
		that2, ok := that.(IndexSeries)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for i := range this.Labels {
		if !this.Labels[i].EqualWiresmith(that1.Labels[i]) {
			return false
		}
	}
	return true
}

func (this *IndexStatsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*IndexStatsRequest)
	if !ok {
		that2, ok := that.(IndexStatsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.Through != that1.Through {
		return false
	}
	if this.Matchers != that1.Matchers {
		return false
	}
	return true
}

func (this *IndexStatsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*IndexStatsResponse)
	if !ok {
		that2, ok := that.(IndexStatsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Streams != that1.Streams {
		return false
	}
	if this.Chunks != that1.Chunks {
		return false
	}
	if this.Bytes != that1.Bytes {
		return false
	}
	if this.Entries != that1.Entries {
		return false
	}
	return true
}

func (this *VolumeRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VolumeRequest)
	if !ok {
		that2, ok := that.(VolumeRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.Through != that1.Through {
		return false
	}
	if this.Matchers != that1.Matchers {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if this.Step != that1.Step {
		return false
	}
	if len(this.TargetLabels) != len(that1.TargetLabels) {
		return false
	}
	for i := range this.TargetLabels {
		if this.TargetLabels[i] != that1.TargetLabels[i] {
			return false
		}
	}
	if this.AggregateBy != that1.AggregateBy {
		return false
	}
	if !this.CachingOpts.Equal(that1.CachingOpts) {
		return false
	}
	return true
}

func (this *VolumeResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VolumeResponse)
	if !ok {
		that2, ok := that.(VolumeResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Volumes) != len(that1.Volumes) {
		return false
	}
	for i := range this.Volumes {
		if !this.Volumes[i].Equal(that1.Volumes[i]) {
			return false
		}
	}
	if this.Limit != that1.Limit {
		return false
	}
	return true
}

func (this *Volume) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Volume)
	if !ok {
		that2, ok := that.(Volume)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Volume != that1.Volume {
		return false
	}
	return true
}

func (this *DetectedFieldsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectedFieldsRequest)
	if !ok {
		that2, ok := that.(DetectedFieldsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	if this.Query != that1.Query {
		return false
	}
	if this.LineLimit != that1.LineLimit {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	if this.Step != that1.Step {
		return false
	}
	if this.Values != that1.Values {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	return true
}

func (this *DetectedFieldsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectedFieldsResponse)
	if !ok {
		that2, ok := that.(DetectedFieldsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Fields) != len(that1.Fields) {
		return false
	}
	for i := range this.Fields {
		if (this.Fields[i] == nil) != (that1.Fields[i] == nil) {
			return false
		}
		if this.Fields[i] != nil && !this.Fields[i].Equal(that1.Fields[i]) {
			return false
		}
	}
	if this.Limit != that1.Limit {
		return false
	}
	if len(this.Values) != len(that1.Values) {
		return false
	}
	for i := range this.Values {
		if this.Values[i] != that1.Values[i] {
			return false
		}
	}
	return true
}

func (this *DetectedField) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectedField)
	if !ok {
		that2, ok := that.(DetectedField)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Cardinality != that1.Cardinality {
		return false
	}
	if len(this.Parsers) != len(that1.Parsers) {
		return false
	}
	for i := range this.Parsers {
		if this.Parsers[i] != that1.Parsers[i] {
			return false
		}
	}
	if !bytes.Equal(this.Sketch, that1.Sketch) {
		return false
	}
	if len(this.JsonPath) != len(that1.JsonPath) {
		return false
	}
	for i := range this.JsonPath {
		if this.JsonPath[i] != that1.JsonPath[i] {
			return false
		}
	}
	return true
}

func (this *DetectedLabelsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectedLabelsRequest)
	if !ok {
		that2, ok := that.(DetectedLabelsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Start.Equal(that1.Start) {
		return false
	}
	if !this.End.Equal(that1.End) {
		return false
	}
	if this.Query != that1.Query {
		return false
	}
	return true
}

func (this *DetectedLabelsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectedLabelsResponse)
	if !ok {
		that2, ok := that.(DetectedLabelsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.DetectedLabels) != len(that1.DetectedLabels) {
		return false
	}
	for i := range this.DetectedLabels {
		if (this.DetectedLabels[i] == nil) != (that1.DetectedLabels[i] == nil) {
			return false
		}
		if this.DetectedLabels[i] != nil && !this.DetectedLabels[i].Equal(that1.DetectedLabels[i]) {
			return false
		}
	}
	return true
}

func (this *DetectedLabel) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectedLabel)
	if !ok {
		that2, ok := that.(DetectedLabel)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if this.Cardinality != that1.Cardinality {
		return false
	}
	if !bytes.Equal(this.Sketch, that1.Sketch) {
		return false
	}
	return true
}
