{{- $isSingleBinary := eq (include "loki.deployment.isSingleBinary" .) "true" -}}
{{- if and $isSingleBinary .Values.singleBinary.persistence.enabled }}
{{- $newStatefulSet := include (print $.Template.BasePath "/single-binary/statefulset.yaml") . | fromYaml -}}
{{- $currentStatefulset := lookup $newStatefulSet.apiVersion $newStatefulSet.kind $newStatefulSet.metadata.namespace $newStatefulSet.metadata.name -}}
{{- $needsRecreation := false -}}
{{- if $currentStatefulset -}}
  {{- if ne (len $newStatefulSet.spec.volumeClaimTemplates) (len $currentStatefulset.spec.volumeClaimTemplates) -}}
    {{- $needsRecreation = true -}}
  {{- else -}}
    {{- range $index, $newVolumeClaimTemplate := $newStatefulSet.spec.volumeClaimTemplates -}}
      {{- $currentVolumeClaimTemplateSpec := dict -}}
        {{- range $oldVolumeClaimTemplate := $currentStatefulset.spec.volumeClaimTemplates -}}
          {{- if eq $oldVolumeClaimTemplate.metadata.name $newVolumeClaimTemplate.metadata.name -}}
            {{- $currentVolumeClaimTemplateSpec = $oldVolumeClaimTemplate.spec -}}
          {{- end -}}
        {{- end }}
      {{- if or (not $currentVolumeClaimTemplateSpec) (ne $newVolumeClaimTemplate.spec.resources.requests.storage $currentVolumeClaimTemplateSpec.resources.requests.storage) -}}
        {{- $needsRecreation = true -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $needsRecreation }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $newStatefulSet.metadata.name }}-recreate-sts
  namespace: {{ $newStatefulSet.metadata.namespace }}
  labels:
    {{- include "loki.singleBinaryLabels" . | nindent 4 }}
    app.kubernetes.io/component: statefulset-recreate-job
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "loki.singleBinarySelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: statefulset-recreate-job
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "loki.serviceAccountName" . }}
      containers:
      - name: recreate-statefulset
        image: {{ include "loki.baseImage" (dict "service" (dict "registry" "docker.io" "repository" "rancher/kubectl" "tag" (.Capabilities.KubeVersion.Version | default "v1.33.0")) "global" .Values.global.image) }}
        command:
        - delete
        - statefulset
        - --namespace={{ $newStatefulSet.metadata.namespace }}
        - --cascade=orphan
        - {{ $newStatefulSet.metadata.name }}
{{- end }}
{{- end }}
