// Code generated by goyacc -l -p syntax -o pkg/logql/syntax/syntax.y.go pkg/logql/syntax/syntax.y. DO NOT EDIT.
package syntax

import __yyfmt__ "fmt"

import (
	"github.com/grafana/loki/v3/pkg/logql/log"
	"github.com/prometheus/prometheus/model/labels"
	"time"
)

type syntaxSymType struct {
	yys   int
	val   interface{}
	bytes uint64
	dur   time.Duration
	op    string
	binOp string
	str   string
	strs  []string

	expr       Expr
	logExpr    LogSelectorExpr
	metricExpr SampleExpr

	matcher                       *labels.Matcher
	matchers                      []*labels.Matcher
	stage                         StageExpr
	stages                        MultiStageExpr
	filterer                      log.LabelFilterer
	filter                        log.LineMatchType
	lineFilterExpr                *LineFilterExpr
	binOpts                       *BinOpOptions
	namedMatcher                  log.NamedLabelMatcher
	namedMatchers                 []log.NamedLabelMatcher
	labelFormat                   log.LabelFmt
	labelsFormat                  []log.LabelFmt
	grouping                      *Grouping
	logRangeExpr                  *LogRangeExpr
	literalExpr                   *LiteralExpr
	labelFormatExpr               *LabelFmtExpr
	labelExtractionExpression     log.LabelExtractionExpr
	labelExtractionExpressionList []log.LabelExtractionExpr
	unwrapExpr                    *UnwrapExpr
	offsetExpr                    *OffsetExpr
}

const BYTES = 57346
const IDENTIFIER = 57347
const STRING = 57348
const NUMBER = 57349
const FUNCTION_FLAG = 57350
const DURATION = 57351
const RANGE = 57352
const MATCHERS = 57353
const LABELS = 57354
const EQ = 57355
const RE = 57356
const NRE = 57357
const NPA = 57358
const OPEN_BRACE = 57359
const CLOSE_BRACE = 57360
const OPEN_BRACKET = 57361
const CLOSE_BRACKET = 57362
const COMMA = 57363
const DOT = 57364
const PIPE_MATCH = 57365
const PIPE_EXACT = 57366
const PIPE_PATTERN = 57367
const OPEN_PARENTHESIS = 57368
const CLOSE_PARENTHESIS = 57369
const BY = 57370
const WITHOUT = 57371
const COUNT_OVER_TIME = 57372
const RATE = 57373
const RATE_COUNTER = 57374
const SUM = 57375
const SORT = 57376
const SORT_DESC = 57377
const AVG = 57378
const MAX = 57379
const MIN = 57380
const COUNT = 57381
const STDDEV = 57382
const STDVAR = 57383
const BOTTOMK = 57384
const TOPK = 57385
const APPROX_TOPK = 57386
const BYTES_OVER_TIME = 57387
const BYTES_RATE = 57388
const BOOL = 57389
const JSON = 57390
const REGEXP = 57391
const LOGFMT = 57392
const PIPE = 57393
const LINE_FMT = 57394
const LABEL_FMT = 57395
const UNWRAP = 57396
const AVG_OVER_TIME = 57397
const SUM_OVER_TIME = 57398
const MIN_OVER_TIME = 57399
const MAX_OVER_TIME = 57400
const STDVAR_OVER_TIME = 57401
const STDDEV_OVER_TIME = 57402
const QUANTILE_OVER_TIME = 57403
const BYTES_CONV = 57404
const DURATION_CONV = 57405
const DURATION_SECONDS_CONV = 57406
const FIRST_OVER_TIME = 57407
const LAST_OVER_TIME = 57408
const ABSENT_OVER_TIME = 57409
const VECTOR = 57410
const LABEL_REPLACE = 57411
const UNPACK = 57412
const OFFSET = 57413
const PATTERN = 57414
const IP = 57415
const ON = 57416
const IGNORING = 57417
const GROUP_LEFT = 57418
const GROUP_RIGHT = 57419
const DECOLORIZE = 57420
const DROP = 57421
const KEEP = 57422
const QUANTILE_SKETCH_OVER_TIME = 57423
const FIRST_OVER_TIME_TS = 57424
const LAST_OVER_TIME_TS = 57425
const OR = 57426
const AND = 57427
const UNLESS = 57428
const CMP_EQ = 57429
const NEQ = 57430
const LT = 57431
const LTE = 57432
const GT = 57433
const GTE = 57434
const ADD = 57435
const SUB = 57436
const MUL = 57437
const DIV = 57438
const MOD = 57439
const POW = 57440

var syntaxToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"BYTES",
	"IDENTIFIER",
	"STRING",
	"NUMBER",
	"FUNCTION_FLAG",
	"DURATION",
	"RANGE",
	"MATCHERS",
	"LABELS",
	"EQ",
	"RE",
	"NRE",
	"NPA",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_BRACKET",
	"CLOSE_BRACKET",
	"COMMA",
	"DOT",
	"PIPE_MATCH",
	"PIPE_EXACT",
	"PIPE_PATTERN",
	"OPEN_PARENTHESIS",
	"CLOSE_PARENTHESIS",
	"BY",
	"WITHOUT",
	"COUNT_OVER_TIME",
	"RATE",
	"RATE_COUNTER",
	"SUM",
	"SORT",
	"SORT_DESC",
	"AVG",
	"MAX",
	"MIN",
	"COUNT",
	"STDDEV",
	"STDVAR",
	"BOTTOMK",
	"TOPK",
	"APPROX_TOPK",
	"BYTES_OVER_TIME",
	"BYTES_RATE",
	"BOOL",
	"JSON",
	"REGEXP",
	"LOGFMT",
	"PIPE",
	"LINE_FMT",
	"LABEL_FMT",
	"UNWRAP",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"STDVAR_OVER_TIME",
	"STDDEV_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"BYTES_CONV",
	"DURATION_CONV",
	"DURATION_SECONDS_CONV",
	"FIRST_OVER_TIME",
	"LAST_OVER_TIME",
	"ABSENT_OVER_TIME",
	"VECTOR",
	"LABEL_REPLACE",
	"UNPACK",
	"OFFSET",
	"PATTERN",
	"IP",
	"ON",
	"IGNORING",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"DECOLORIZE",
	"DROP",
	"KEEP",
	"QUANTILE_SKETCH_OVER_TIME",
	"FIRST_OVER_TIME_TS",
	"LAST_OVER_TIME_TS",
	"OR",
	"AND",
	"UNLESS",
	"CMP_EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}
var syntaxStatenames = [...]string{}

const syntaxEofCode = 1
const syntaxErrCode = 2
const syntaxInitialStackSize = 16

var syntaxExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const syntaxPrivate = 57344

const syntaxLast = 681

var syntaxAct = [...]int{

	287, 228, 88, 4, 215, 68, 186, 130, 204, 193,
	80, 201, 237, 67, 203, 5, 156, 191, 81, 2,
	60, 84, 52, 53, 54, 61, 62, 65, 66, 63,
	64, 55, 56, 57, 58, 59, 60, 10, 53, 54,
	61, 62, 65, 66, 63, 64, 55, 56, 57, 58,
	59, 60, 61, 62, 65, 66, 63, 64, 55, 56,
	57, 58, 59, 60, 55, 56, 57, 58, 59, 60,
	282, 280, 143, 113, 16, 217, 279, 119, 57, 58,
	59, 60, 216, 140, 265, 363, 221, 16, 144, 264,
	290, 160, 295, 261, 292, 220, 16, 165, 260, 188,
	170, 171, 158, 277, 134, 290, 16, 363, 276, 71,
	208, 154, 155, 98, 167, 152, 154, 155, 172, 173,
	174, 175, 176, 177, 178, 179, 180, 181, 182, 183,
	184, 185, 274, 168, 169, 16, 383, 273, 378, 336,
	291, 198, 76, 78, 195, 337, 206, 206, 145, 146,
	73, 74, 75, 263, 207, 146, 366, 343, 336, 219,
	17, 18, 259, 187, 271, 291, 235, 16, 87, 270,
	89, 90, 229, 17, 18, 231, 232, 240, 230, 114,
	292, 292, 17, 18, 214, 209, 212, 213, 210, 211,
	153, 304, 17, 18, 248, 249, 250, 353, 290, 292,
	89, 90, 339, 340, 341, 304, 292, 268, 252, 224,
	16, 352, 267, 304, 304, 77, 371, 76, 78, 351,
	350, 17, 18, 140, 370, 73, 74, 75, 285, 288,
	360, 294, 368, 297, 328, 113, 300, 119, 301, 188,
	140, 289, 158, 286, 134, 298, 262, 266, 269, 272,
	275, 278, 281, 17, 18, 140, 188, 308, 310, 313,
	315, 134, 255, 316, 293, 356, 206, 322, 318, 76,
	78, 188, 346, 224, 76, 78, 134, 73, 74, 75,
	327, 344, 73, 74, 75, 302, 239, 325, 243, 329,
	77, 331, 333, 239, 335, 113, 17, 18, 299, 334,
	345, 330, 189, 187, 113, 230, 239, 347, 314, 224,
	230, 239, 304, 239, 13, 312, 304, 239, 306, 189,
	187, 233, 305, 159, 140, 148, 147, 257, 311, 324,
	323, 357, 358, 309, 225, 241, 113, 359, 381, 238,
	157, 283, 77, 361, 362, 134, 247, 77, 246, 367,
	13, 245, 244, 218, 164, 163, 227, 16, 162, 159,
	94, 76, 78, 373, 93, 374, 375, 13, 86, 73,
	74, 75, 377, 296, 349, 253, 6, 379, 303, 258,
	21, 22, 23, 39, 48, 49, 40, 42, 43, 41,
	44, 45, 46, 47, 50, 24, 25, 230, 256, 242,
	234, 226, 254, 376, 150, 26, 27, 28, 29, 30,
	31, 32, 85, 365, 364, 33, 34, 35, 51, 19,
	149, 342, 332, 151, 166, 83, 236, 194, 320, 321,
	251, 36, 37, 38, 77, 194, 13, 382, 192, 92,
	91, 3, 380, 17, 18, 6, 369, 355, 79, 21,
	22, 23, 39, 48, 49, 40, 42, 43, 41, 44,
	45, 46, 47, 50, 24, 25, 354, 326, 319, 317,
	307, 202, 200, 284, 26, 27, 28, 29, 30, 31,
	32, 223, 222, 221, 33, 34, 35, 51, 19, 220,
	199, 197, 196, 97, 372, 161, 348, 205, 194, 85,
	36, 37, 38, 202, 96, 13, 190, 20, 82, 72,
	131, 132, 17, 18, 6, 141, 133, 142, 21, 22,
	23, 39, 48, 49, 40, 42, 43, 41, 44, 45,
	46, 47, 50, 24, 25, 15, 338, 14, 69, 124,
	123, 122, 121, 26, 27, 28, 29, 30, 31, 32,
	120, 118, 117, 33, 34, 35, 51, 19, 116, 293,
	115, 12, 227, 11, 76, 78, 9, 76, 78, 36,
	37, 38, 73, 74, 75, 73, 74, 75, 76, 78,
	140, 17, 18, 8, 7, 1, 73, 74, 75, 0,
	0, 140, 0, 0, 0, 0, 0, 0, 0, 0,
	230, 134, 0, 230, 0, 0, 0, 0, 0, 0,
	0, 0, 134, 95, 70, 0, 0, 0, 0, 0,
	0, 0, 0, 126, 127, 125, 0, 135, 137, 295,
	0, 0, 0, 0, 126, 127, 125, 77, 135, 137,
	77, 0, 0, 0, 0, 128, 0, 129, 0, 0,
	0, 77, 0, 136, 138, 139, 128, 0, 129, 0,
	0, 0, 0, 0, 136, 138, 139, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112,
}
var syntaxPact = [...]int{

	350, -1000, -62, -1000, -1000, 563, 350, -1000, -1000, -1000,
	-1000, -1000, -1000, 407, 342, 142, -1000, 433, 432, 338,
	334, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 66, 66, 66, 66, 66, 66, 66, 66,
	66, 66, 66, 66, 66, 66, 66, 563, -1000, 202,
	586, -12, 82, -1000, -1000, -1000, -1000, -1000, -1000, 299,
	298, -62, 402, -1000, -1000, 102, 333, 488, 332, 329,
	328, -1000, -1000, 350, 417, 350, 59, 24, -1000, 350,
	350, 350, 350, 350, 350, 350, 350, 350, 350, 350,
	350, 350, 350, -1000, -12, -1000, -1000, -1000, -1000, 218,
	-1000, -1000, -1000, -1000, -1000, 430, 493, 486, -1000, 485,
	-1000, -1000, -1000, -1000, 319, 484, -1000, 498, 492, 492,
	97, -1000, -1000, 76, -1000, 327, -1000, -1000, -1000, -1000,
	-1000, 494, 483, 477, 476, 475, 307, 380, 552, 297,
	294, 379, 419, 312, 308, 378, 261, -47, 326, 325,
	322, 320, -35, -35, -17, -17, -78, -78, -78, -78,
	-29, -29, -29, -29, -29, -29, 218, 319, 319, 319,
	422, 354, -1000, -1000, 389, 354, -1000, -1000, 235, -1000,
	377, -1000, 314, 358, -1000, 102, -1000, 358, 89, 80,
	203, 160, 128, 99, 67, -1000, -14, 315, 467, -1000,
	-1000, -1000, -1000, -1000, -1000, 172, 297, 127, 155, 549,
	575, 346, 271, 172, 350, 258, 357, 295, -1000, -1000,
	291, -1000, 464, -1000, 306, 301, 288, 281, 250, 218,
	78, -1000, 354, 493, 463, -1000, 466, 423, 492, 304,
	-1000, -1000, -1000, 303, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 76, 461, 253, -1000, 207, 259, 43, 259,
	413, 19, 319, 19, 148, 140, 411, 130, 254, -1000,
	-1000, 245, -1000, 350, 491, -1000, -1000, 353, 193, -1000,
	192, -1000, -1000, 184, -1000, 170, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 460, 441, -1000, 238, -1000, 172, 43,
	259, 43, -1000, -1000, 218, -1000, 19, -1000, 204, -1000,
	-1000, -1000, 34, 404, 403, 129, 172, 205, -1000, 440,
	-1000, -1000, -1000, -1000, 197, 189, -1000, -1000, 43, -1000,
	489, 56, 43, 38, 19, 19, 393, -1000, -1000, 351,
	-1000, -1000, 111, 43, -1000, -1000, 19, 436, -1000, -1000,
	317, 431, 109, -1000,
}
var syntaxPgo = [...]int{

	0, 585, 18, 441, 3, 584, 583, 566, 563, 561,
	5, 560, 558, 552, 551, 550, 542, 541, 540, 539,
	13, 109, 538, 4, 537, 536, 535, 75, 517, 516,
	515, 6, 511, 510, 509, 7, 508, 15, 507, 12,
	506, 613, 504, 493, 8, 14, 11, 472, 2, 16,
	37, 9, 17, 1, 0,
}
var syntaxR1 = [...]int{

	0, 1, 2, 2, 3, 3, 3, 4, 4, 4,
	4, 4, 4, 4, 49, 49, 49, 49, 49, 49,
	49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
	49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
	53, 53, 53, 25, 25, 25, 5, 5, 5, 5,
	6, 6, 6, 6, 6, 6, 8, 37, 37, 37,
	36, 36, 35, 35, 35, 35, 20, 20, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 34,
	34, 34, 34, 34, 34, 27, 23, 23, 23, 21,
	21, 21, 22, 22, 40, 40, 11, 11, 12, 12,
	12, 12, 13, 14, 14, 15, 16, 46, 46, 47,
	47, 47, 17, 31, 31, 31, 31, 31, 31, 31,
	31, 31, 51, 51, 52, 52, 33, 33, 32, 32,
	30, 30, 30, 30, 30, 30, 30, 28, 28, 28,
	28, 28, 28, 28, 29, 29, 29, 29, 29, 29,
	29, 44, 44, 45, 45, 18, 19, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 42, 42, 43, 43, 43, 43, 41, 41,
	41, 41, 41, 41, 41, 41, 50, 50, 50, 9,
	38, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	26, 26, 26, 24, 24, 24, 24, 24, 24, 24,
	24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
	24, 54, 39, 39, 48, 48, 48, 48,
}
var syntaxR2 = [...]int{

	0, 1, 1, 1, 1, 2, 3, 1, 1, 1,
	1, 1, 1, 3, 2, 3, 4, 5, 3, 4,
	5, 6, 3, 4, 5, 6, 3, 4, 5, 6,
	4, 5, 6, 7, 3, 4, 4, 5, 3, 2,
	3, 6, 3, 1, 1, 1, 4, 6, 5, 7,
	4, 5, 5, 6, 7, 7, 12, 3, 3, 2,
	1, 3, 3, 3, 3, 3, 1, 2, 1, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 3, 4, 2,
	5, 3, 1, 2, 1, 2, 1, 2, 1, 2,
	1, 2, 2, 3, 2, 2, 1, 3, 3, 1,
	3, 3, 2, 1, 1, 1, 1, 3, 2, 3,
	3, 3, 3, 1, 1, 3, 6, 6, 1, 1,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 1, 1, 1, 3, 2, 2, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 0, 1, 5, 4, 5, 4, 1, 1,
	2, 4, 5, 2, 4, 5, 1, 2, 2, 4,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 1, 3, 4, 4, 3, 3,
}
var syntaxChk = [...]int{

	-1000, -1, -2, -3, -4, -37, 26, -5, -6, -7,
	-50, -8, -9, 17, -24, -26, 7, 93, 94, 69,
	-38, 30, 31, 32, 45, 46, 55, 56, 57, 58,
	59, 60, 61, 65, 66, 67, 81, 82, 83, 33,
	36, 39, 37, 38, 40, 41, 42, 43, 34, 35,
	44, 68, 84, 85, 86, 93, 94, 95, 96, 97,
	98, 87, 88, 91, 92, 89, 90, -20, -10, -22,
	51, -21, -34, 23, 24, 25, 15, 88, 16, -3,
	-4, -2, -36, 18, -35, 5, 26, 26, -48, 28,
	29, 7, 7, 26, 26, -41, -42, -43, 47, -41,
	-41, -41, -41, -41, -41, -41, -41, -41, -41, -41,
	-41, -41, -41, -10, -21, -11, -12, -13, -14, -31,
	-15, -16, -17, -18, -19, 50, 48, 49, 70, 72,
	-35, -33, -32, -29, 26, 52, 78, 53, 79, 80,
	5, -30, -28, 84, 6, -27, 73, 27, 27, 18,
	2, 21, 13, 88, 14, 15, -49, 7, -37, 26,
	-4, 7, 26, 26, 26, -4, 7, -2, 74, 75,
	76, 77, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -31, 85, 21, 84,
	-40, -52, 8, -51, 5, -52, 6, 6, -31, 6,
	-47, -46, 5, -45, -44, 5, -35, -45, 13, 88,
	91, 92, 89, 90, 87, -23, 6, -27, 26, -35,
	6, 6, 6, 6, 2, 27, 21, 10, -53, -20,
	51, -37, -49, 27, 21, -4, 7, -39, 27, 5,
	-39, 27, 21, 27, 26, 26, 26, 26, -31, -31,
	-31, 8, -52, 21, 13, 27, 21, 13, 21, 73,
	9, 4, -50, 73, 9, 4, -50, 9, 4, -50,
	9, 4, -50, 9, 4, -50, 9, 4, -50, 9,
	4, -50, 84, 26, 6, -48, -49, -54, -53, -20,
	71, 10, 51, 10, -53, 54, 27, -53, -20, 27,
	-48, -4, 27, 21, 21, 27, 27, 6, -39, 27,
	-39, 27, 27, -39, 27, -39, -51, 6, -46, 2,
	5, 6, -44, 26, 26, -23, 6, 27, 27, -53,
	-20, -53, 9, -54, -31, -54, 10, 5, -25, 62,
	63, 64, 10, 27, 27, -53, 27, -4, 5, 21,
	27, 27, 27, 27, 6, 6, 27, -48, -53, -54,
	26, -54, -53, 51, 10, 10, 27, -48, 27, 6,
	27, 27, 5, -53, -54, -54, 10, 21, 27, -54,
	6, 21, 6, 27,
}
var syntaxDef = [...]int{

	0, -2, 1, 2, 3, 4, 0, 7, 8, 9,
	10, 11, 12, 0, 0, 0, 186, 0, 0, 0,
	0, 203, 204, 205, 206, 207, 208, 209, 210, 211,
	212, 213, 214, 215, 216, 217, 218, 219, 220, 191,
	192, 193, 194, 195, 196, 197, 198, 199, 200, 201,
	202, 190, 172, 172, 172, 172, 172, 172, 172, 172,
	172, 172, 172, 172, 172, 172, 172, 5, 66, 68,
	0, 92, 0, 79, 80, 81, 82, 83, 84, 2,
	3, 0, 0, 59, 60, 0, 0, 0, 0, 0,
	0, 187, 188, 0, 0, 0, 178, 179, 173, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 67, 93, 69, 70, 71, 72, 73,
	74, 75, 76, 77, 78, 96, 98, 0, 100, 0,
	113, 114, 115, 116, 0, 0, 106, 0, 0, 0,
	0, 128, 129, 0, 89, 0, 85, 6, 13, 57,
	58, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 186, 0, 0, 0, 3, 0, 157, 0, 0,
	180, 183, 158, 159, 160, 161, 162, 163, 164, 165,
	166, 167, 168, 169, 170, 171, 118, 0, 0, 0,
	97, 104, 94, 124, 123, 102, 99, 101, 0, 105,
	112, 109, 0, 155, 153, 151, 152, 156, 0, 0,
	0, 0, 0, 0, 0, 91, 86, 0, 0, 61,
	62, 63, 64, 65, 39, 46, 0, 14, 0, 0,
	0, 0, 0, 50, 0, 3, 186, 0, 226, 222,
	0, 227, 0, 189, 0, 0, 0, 0, 119, 120,
	121, 95, 103, 0, 0, 117, 0, 0, 0, 0,
	135, 142, 149, 0, 134, 141, 148, 130, 137, 144,
	131, 138, 145, 132, 139, 146, 133, 140, 147, 136,
	143, 150, 0, 0, 0, 48, 0, 15, 18, 34,
	0, 22, 0, 26, 0, 0, 0, 0, 0, 38,
	52, 3, 51, 0, 0, 224, 225, 0, 0, 175,
	0, 177, 181, 0, 184, 0, 125, 122, 110, 111,
	107, 108, 154, 0, 0, 87, 0, 90, 47, 19,
	35, 36, 221, 23, 42, 27, 30, 40, 0, 43,
	44, 45, 16, 0, 0, 0, 53, 3, 223, 0,
	174, 176, 182, 185, 0, 0, 88, 49, 37, 31,
	0, 17, 20, 0, 24, 28, 0, 54, 55, 0,
	126, 127, 0, 21, 25, 29, 32, 0, 41, 33,
	0, 0, 0, 56,
}
var syntaxTok1 = [...]int{

	1,
}
var syntaxTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98,
}
var syntaxTok3 = [...]int{
	0,
}

var syntaxErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	syntaxDebug        = 0
	syntaxErrorVerbose = false
)

type syntaxLexer interface {
	Lex(lval *syntaxSymType) int
	Error(s string)
}

type syntaxParser interface {
	Parse(syntaxLexer) int
	Lookahead() int
}

type syntaxParserImpl struct {
	lval  syntaxSymType
	stack [syntaxInitialStackSize]syntaxSymType
	char  int
}

func (p *syntaxParserImpl) Lookahead() int {
	return p.char
}

func syntaxNewParser() syntaxParser {
	return &syntaxParserImpl{}
}

const syntaxFlag = -1000

func syntaxTokname(c int) string {
	if c >= 1 && c-1 < len(syntaxToknames) {
		if syntaxToknames[c-1] != "" {
			return syntaxToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func syntaxStatname(s int) string {
	if s >= 0 && s < len(syntaxStatenames) {
		if syntaxStatenames[s] != "" {
			return syntaxStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func syntaxErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !syntaxErrorVerbose {
		return "syntax error"
	}

	for _, e := range syntaxErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + syntaxTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := syntaxPact[state]
	for tok := TOKSTART; tok-1 < len(syntaxToknames); tok++ {
		if n := base + tok; n >= 0 && n < syntaxLast && syntaxChk[syntaxAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if syntaxDef[state] == -2 {
		i := 0
		for syntaxExca[i] != -1 || syntaxExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; syntaxExca[i] >= 0; i += 2 {
			tok := syntaxExca[i]
			if tok < TOKSTART || syntaxExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if syntaxExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += syntaxTokname(tok)
	}
	return res
}

func syntaxlex1(lex syntaxLexer, lval *syntaxSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = syntaxTok1[0]
		goto out
	}
	if char < len(syntaxTok1) {
		token = syntaxTok1[char]
		goto out
	}
	if char >= syntaxPrivate {
		if char < syntaxPrivate+len(syntaxTok2) {
			token = syntaxTok2[char-syntaxPrivate]
			goto out
		}
	}
	for i := 0; i < len(syntaxTok3); i += 2 {
		token = syntaxTok3[i+0]
		if token == char {
			token = syntaxTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = syntaxTok2[1] /* unknown char */
	}
	if syntaxDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", syntaxTokname(token), uint(char))
	}
	return char, token
}

func syntaxParse(syntaxlex syntaxLexer) int {
	return syntaxNewParser().Parse(syntaxlex)
}

func (syntaxrcvr *syntaxParserImpl) Parse(syntaxlex syntaxLexer) int {
	var syntaxn int
	var syntaxVAL syntaxSymType
	var syntaxDollar []syntaxSymType
	_ = syntaxDollar // silence set and not used
	syntaxS := syntaxrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	syntaxstate := 0
	syntaxrcvr.char = -1
	syntaxtoken := -1 // syntaxrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		syntaxstate = -1
		syntaxrcvr.char = -1
		syntaxtoken = -1
	}()
	syntaxp := -1
	goto syntaxstack

ret0:
	return 0

ret1:
	return 1

syntaxstack:
	/* put a state and value onto the stack */
	if syntaxDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", syntaxTokname(syntaxtoken), syntaxStatname(syntaxstate))
	}

	syntaxp++
	if syntaxp >= len(syntaxS) {
		nyys := make([]syntaxSymType, len(syntaxS)*2)
		copy(nyys, syntaxS)
		syntaxS = nyys
	}
	syntaxS[syntaxp] = syntaxVAL
	syntaxS[syntaxp].yys = syntaxstate

syntaxnewstate:
	syntaxn = syntaxPact[syntaxstate]
	if syntaxn <= syntaxFlag {
		goto syntaxdefault /* simple state */
	}
	if syntaxrcvr.char < 0 {
		syntaxrcvr.char, syntaxtoken = syntaxlex1(syntaxlex, &syntaxrcvr.lval)
	}
	syntaxn += syntaxtoken
	if syntaxn < 0 || syntaxn >= syntaxLast {
		goto syntaxdefault
	}
	syntaxn = syntaxAct[syntaxn]
	if syntaxChk[syntaxn] == syntaxtoken { /* valid shift */
		syntaxrcvr.char = -1
		syntaxtoken = -1
		syntaxVAL = syntaxrcvr.lval
		syntaxstate = syntaxn
		if Errflag > 0 {
			Errflag--
		}
		goto syntaxstack
	}

syntaxdefault:
	/* default state action */
	syntaxn = syntaxDef[syntaxstate]
	if syntaxn == -2 {
		if syntaxrcvr.char < 0 {
			syntaxrcvr.char, syntaxtoken = syntaxlex1(syntaxlex, &syntaxrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if syntaxExca[xi+0] == -1 && syntaxExca[xi+1] == syntaxstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			syntaxn = syntaxExca[xi+0]
			if syntaxn < 0 || syntaxn == syntaxtoken {
				break
			}
		}
		syntaxn = syntaxExca[xi+1]
		if syntaxn < 0 {
			goto ret0
		}
	}
	if syntaxn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			syntaxlex.Error(syntaxErrorMessage(syntaxstate, syntaxtoken))
			Nerrs++
			if syntaxDebug >= 1 {
				__yyfmt__.Printf("%s", syntaxStatname(syntaxstate))
				__yyfmt__.Printf(" saw %s\n", syntaxTokname(syntaxtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for syntaxp >= 0 {
				syntaxn = syntaxPact[syntaxS[syntaxp].yys] + syntaxErrCode
				if syntaxn >= 0 && syntaxn < syntaxLast {
					syntaxstate = syntaxAct[syntaxn] /* simulate a shift of "error" */
					if syntaxChk[syntaxstate] == syntaxErrCode {
						goto syntaxstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if syntaxDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", syntaxS[syntaxp].yys)
				}
				syntaxp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if syntaxDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", syntaxTokname(syntaxtoken))
			}
			if syntaxtoken == syntaxEofCode {
				goto ret1
			}
			syntaxrcvr.char = -1
			syntaxtoken = -1
			goto syntaxnewstate /* try again in the same state */
		}
	}

	/* reduction by production syntaxn */
	if syntaxDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", syntaxn, syntaxStatname(syntaxstate))
	}

	syntaxnt := syntaxn
	syntaxpt := syntaxp
	_ = syntaxpt // guard against "declared and not used"

	syntaxp -= syntaxR2[syntaxn]
	// syntaxp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if syntaxp+1 >= len(syntaxS) {
		nyys := make([]syntaxSymType, len(syntaxS)*2)
		copy(nyys, syntaxS)
		syntaxS = nyys
	}
	syntaxVAL = syntaxS[syntaxp+1]

	/* consult goto table to find next state */
	syntaxn = syntaxR1[syntaxn]
	syntaxg := syntaxPgo[syntaxn]
	syntaxj := syntaxg + syntaxS[syntaxp].yys + 1

	if syntaxj >= syntaxLast {
		syntaxstate = syntaxAct[syntaxg]
	} else {
		syntaxstate = syntaxAct[syntaxj]
		if syntaxChk[syntaxstate] != -syntaxn {
			syntaxstate = syntaxAct[syntaxg]
		}
	}
	// dummy call; replaced with literal code
	switch syntaxnt {

	case 1:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxlex.(*parser).expr = syntaxDollar[1].expr
		}
	case 2:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.expr = syntaxDollar[1].logExpr
		}
	case 3:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.expr = syntaxDollar[1].metricExpr
		}
	case 4:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.logExpr = newMatcherExpr(syntaxDollar[1].matchers)
		}
	case 5:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.logExpr = newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].stages)
		}
	case 6:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.logExpr = syntaxDollar[2].logExpr
		}
	case 7:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = syntaxDollar[1].metricExpr
		}
	case 8:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = syntaxDollar[1].metricExpr
		}
	case 9:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = syntaxDollar[1].metricExpr
		}
	case 10:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = syntaxDollar[1].literalExpr
		}
	case 11:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = syntaxDollar[1].metricExpr
		}
	case 12:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = syntaxDollar[1].metricExpr
		}
	case 13:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = syntaxDollar[2].metricExpr
		}
	case 14:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].dur, nil, nil)
		}
	case 15:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].dur, nil, syntaxDollar[3].offsetExpr)
		}
	case 16:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[4].dur, nil, nil)
		}
	case 17:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[4].dur, nil, syntaxDollar[5].offsetExpr)
		}
	case 18:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].dur, syntaxDollar[3].unwrapExpr, nil)
		}
	case 19:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].dur, syntaxDollar[4].unwrapExpr, syntaxDollar[3].offsetExpr)
		}
	case 20:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[4].dur, syntaxDollar[5].unwrapExpr, nil)
		}
	case 21:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[4].dur, syntaxDollar[6].unwrapExpr, syntaxDollar[5].offsetExpr)
		}
	case 22:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[3].dur, syntaxDollar[2].unwrapExpr, nil)
		}
	case 23:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[3].dur, syntaxDollar[2].unwrapExpr, syntaxDollar[4].offsetExpr)
		}
	case 24:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[5].dur, syntaxDollar[3].unwrapExpr, nil)
		}
	case 25:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[5].dur, syntaxDollar[3].unwrapExpr, syntaxDollar[6].offsetExpr)
		}
	case 26:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].stages), syntaxDollar[3].dur, nil, nil)
		}
	case 27:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].stages), syntaxDollar[3].dur, nil, syntaxDollar[4].offsetExpr)
		}
	case 28:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[3].stages), syntaxDollar[5].dur, nil, nil)
		}
	case 29:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[3].stages), syntaxDollar[5].dur, nil, syntaxDollar[6].offsetExpr)
		}
	case 30:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].stages), syntaxDollar[4].dur, syntaxDollar[3].unwrapExpr, nil)
		}
	case 31:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[2].stages), syntaxDollar[4].dur, syntaxDollar[3].unwrapExpr, syntaxDollar[5].offsetExpr)
		}
	case 32:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[3].stages), syntaxDollar[6].dur, syntaxDollar[4].unwrapExpr, nil)
		}
	case 33:
		syntaxDollar = syntaxS[syntaxpt-7 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[2].matchers), syntaxDollar[3].stages), syntaxDollar[6].dur, syntaxDollar[4].unwrapExpr, syntaxDollar[7].offsetExpr)
		}
	case 34:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[3].stages), syntaxDollar[2].dur, nil, nil)
		}
	case 35:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[4].stages), syntaxDollar[2].dur, nil, syntaxDollar[3].offsetExpr)
		}
	case 36:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[3].stages), syntaxDollar[2].dur, syntaxDollar[4].unwrapExpr, nil)
		}
	case 37:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = newLogRange(newPipelineExpr(newMatcherExpr(syntaxDollar[1].matchers), syntaxDollar[4].stages), syntaxDollar[2].dur, syntaxDollar[5].unwrapExpr, syntaxDollar[3].offsetExpr)
		}
	case 38:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.logRangeExpr = syntaxDollar[2].logRangeExpr
		}
	case 40:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.unwrapExpr = newUnwrapExpr(syntaxDollar[3].str, "")
		}
	case 41:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.unwrapExpr = newUnwrapExpr(syntaxDollar[5].str, syntaxDollar[3].op)
		}
	case 42:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.unwrapExpr = syntaxDollar[1].unwrapExpr.addPostFilter(syntaxDollar[3].filterer)
		}
	case 43:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpConvBytes
		}
	case 44:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpConvDuration
		}
	case 45:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpConvDurationSeconds
		}
	case 46:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = newRangeAggregationExpr(syntaxDollar[3].logRangeExpr, syntaxDollar[1].op, nil, nil)
		}
	case 47:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = newRangeAggregationExpr(syntaxDollar[5].logRangeExpr, syntaxDollar[1].op, nil, &syntaxDollar[3].str)
		}
	case 48:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = newRangeAggregationExpr(syntaxDollar[3].logRangeExpr, syntaxDollar[1].op, syntaxDollar[5].grouping, nil)
		}
	case 49:
		syntaxDollar = syntaxS[syntaxpt-7 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = newRangeAggregationExpr(syntaxDollar[5].logRangeExpr, syntaxDollar[1].op, syntaxDollar[7].grouping, &syntaxDollar[3].str)
		}
	case 50:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewVectorAggregationExpr(syntaxDollar[3].metricExpr, syntaxDollar[1].op, nil, nil)
		}
	case 51:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewVectorAggregationExpr(syntaxDollar[4].metricExpr, syntaxDollar[1].op, syntaxDollar[2].grouping, nil)
		}
	case 52:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewVectorAggregationExpr(syntaxDollar[3].metricExpr, syntaxDollar[1].op, syntaxDollar[5].grouping, nil)
		}
	case 53:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewVectorAggregationExpr(syntaxDollar[5].metricExpr, syntaxDollar[1].op, nil, &syntaxDollar[3].str)
		}
	case 54:
		syntaxDollar = syntaxS[syntaxpt-7 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewVectorAggregationExpr(syntaxDollar[5].metricExpr, syntaxDollar[1].op, syntaxDollar[7].grouping, &syntaxDollar[3].str)
		}
	case 55:
		syntaxDollar = syntaxS[syntaxpt-7 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewVectorAggregationExpr(syntaxDollar[6].metricExpr, syntaxDollar[1].op, syntaxDollar[2].grouping, &syntaxDollar[4].str)
		}
	case 56:
		syntaxDollar = syntaxS[syntaxpt-12 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewLabelReplaceExpr(syntaxDollar[3].metricExpr, syntaxDollar[5].str, syntaxDollar[7].str, syntaxDollar[9].str, syntaxDollar[11].str)
		}
	case 57:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.matchers = syntaxDollar[2].matchers
		}
	case 58:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.matchers = syntaxDollar[2].matchers
		}
	case 59:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
		}
	case 60:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.matchers = []*labels.Matcher{syntaxDollar[1].matcher}
		}
	case 61:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.matchers = append(syntaxDollar[1].matchers, syntaxDollar[3].matcher)
		}
	case 62:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.matcher = mustNewMatcher(labels.MatchEqual, syntaxDollar[1].str, syntaxDollar[3].str)
		}
	case 63:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.matcher = mustNewMatcher(labels.MatchNotEqual, syntaxDollar[1].str, syntaxDollar[3].str)
		}
	case 64:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.matcher = mustNewMatcher(labels.MatchRegexp, syntaxDollar[1].str, syntaxDollar[3].str)
		}
	case 65:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.matcher = mustNewMatcher(labels.MatchNotRegexp, syntaxDollar[1].str, syntaxDollar[3].str)
		}
	case 66:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.stages = MultiStageExpr{syntaxDollar[1].stage}
		}
	case 67:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stages = append(syntaxDollar[1].stages, syntaxDollar[2].stage)
		}
	case 68:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[1].lineFilterExpr
		}
	case 69:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 70:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 71:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 72:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 73:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = &LabelFilterExpr{LabelFilterer: syntaxDollar[2].filterer}
		}
	case 74:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 75:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 76:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 77:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 78:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = syntaxDollar[2].stage
		}
	case 79:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filter = log.LineMatchRegexp
		}
	case 80:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filter = log.LineMatchEqual
		}
	case 81:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filter = log.LineMatchPattern
		}
	case 82:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filter = log.LineMatchNotRegexp
		}
	case 83:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filter = log.LineMatchNotEqual
		}
	case 84:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filter = log.LineMatchNotPattern
		}
	case 85:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpFilterIP
		}
	case 86:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = newLineFilterExpr(log.LineMatchEqual, "", syntaxDollar[1].str)
		}
	case 87:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = newOrLineFilterExpr(newLineFilterExpr(log.LineMatchEqual, "", syntaxDollar[1].str), syntaxDollar[3].lineFilterExpr)
		}
	case 88:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = newLineFilterExpr(log.LineMatchEqual, syntaxDollar[1].op, syntaxDollar[3].str)
		}
	case 89:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = newLineFilterExpr(syntaxDollar[1].filter, "", syntaxDollar[2].str)
		}
	case 90:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = newLineFilterExpr(syntaxDollar[1].filter, syntaxDollar[2].op, syntaxDollar[4].str)
		}
	case 91:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = newOrLineFilterExpr(syntaxDollar[1].lineFilterExpr, syntaxDollar[3].lineFilterExpr)
		}
	case 92:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = syntaxDollar[1].lineFilterExpr
		}
	case 93:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.lineFilterExpr = newNestedLineFilterExpr(syntaxDollar[1].lineFilterExpr, syntaxDollar[2].lineFilterExpr)
		}
	case 94:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.strs = []string{syntaxDollar[1].str}
		}
	case 95:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.strs = append(syntaxDollar[1].strs, syntaxDollar[2].str)
		}
	case 96:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.stage = newLogfmtParserExpr(nil)
		}
	case 97:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newLogfmtParserExpr(syntaxDollar[2].strs)
		}
	case 98:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.stage = newLabelParserExpr(OpParserTypeJSON, "")
		}
	case 99:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newLabelParserExpr(OpParserTypeRegexp, syntaxDollar[2].str)
		}
	case 100:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.stage = newLabelParserExpr(OpParserTypeUnpack, "")
		}
	case 101:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newLabelParserExpr(OpParserTypePattern, syntaxDollar[2].str)
		}
	case 102:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newJSONExpressionParser(syntaxDollar[2].labelExtractionExpressionList)
		}
	case 103:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.stage = newLogfmtExpressionParser(syntaxDollar[3].labelExtractionExpressionList, syntaxDollar[2].strs)
		}
	case 104:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newLogfmtExpressionParser(syntaxDollar[2].labelExtractionExpressionList, nil)
		}
	case 105:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newLineFmtExpr(syntaxDollar[2].str)
		}
	case 106:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.stage = newDecolorizeExpr()
		}
	case 107:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.labelFormat = log.NewRenameLabelFmt(syntaxDollar[1].str, syntaxDollar[3].str)
		}
	case 108:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.labelFormat = log.NewTemplateLabelFmt(syntaxDollar[1].str, syntaxDollar[3].str)
		}
	case 109:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.labelsFormat = []log.LabelFmt{syntaxDollar[1].labelFormat}
		}
	case 110:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.labelsFormat = append(syntaxDollar[1].labelsFormat, syntaxDollar[3].labelFormat)
		}
	case 112:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newLabelFmtExpr(syntaxDollar[2].labelsFormat)
		}
	case 113:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewStringLabelFilter(syntaxDollar[1].matcher)
		}
	case 114:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filterer = syntaxDollar[1].filterer
		}
	case 115:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filterer = syntaxDollar[1].filterer
		}
	case 116:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filterer = syntaxDollar[1].filterer
		}
	case 117:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = syntaxDollar[2].filterer
		}
	case 118:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewAndLabelFilter(syntaxDollar[1].filterer, syntaxDollar[2].filterer)
		}
	case 119:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewAndLabelFilter(syntaxDollar[1].filterer, syntaxDollar[3].filterer)
		}
	case 120:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewAndLabelFilter(syntaxDollar[1].filterer, syntaxDollar[3].filterer)
		}
	case 121:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewOrLabelFilter(syntaxDollar[1].filterer, syntaxDollar[3].filterer)
		}
	case 122:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.labelExtractionExpression = log.NewLabelExtractionExpr(syntaxDollar[1].str, syntaxDollar[3].str)
		}
	case 123:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.labelExtractionExpression = log.NewLabelExtractionExpr(syntaxDollar[1].str, syntaxDollar[1].str)
		}
	case 124:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.labelExtractionExpressionList = []log.LabelExtractionExpr{syntaxDollar[1].labelExtractionExpression}
		}
	case 125:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.labelExtractionExpressionList = append(syntaxDollar[1].labelExtractionExpressionList, syntaxDollar[3].labelExtractionExpression)
		}
	case 126:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewIPLabelFilter(syntaxDollar[5].str, syntaxDollar[1].str, log.LabelFilterEqual)
		}
	case 127:
		syntaxDollar = syntaxS[syntaxpt-6 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewIPLabelFilter(syntaxDollar[5].str, syntaxDollar[1].str, log.LabelFilterNotEqual)
		}
	case 128:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filterer = syntaxDollar[1].filterer
		}
	case 129:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.filterer = syntaxDollar[1].filterer
		}
	case 130:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewDurationLabelFilter(log.LabelFilterGreaterThan, syntaxDollar[1].str, syntaxDollar[3].dur)
		}
	case 131:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewDurationLabelFilter(log.LabelFilterGreaterThanOrEqual, syntaxDollar[1].str, syntaxDollar[3].dur)
		}
	case 132:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewDurationLabelFilter(log.LabelFilterLesserThan, syntaxDollar[1].str, syntaxDollar[3].dur)
		}
	case 133:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewDurationLabelFilter(log.LabelFilterLesserThanOrEqual, syntaxDollar[1].str, syntaxDollar[3].dur)
		}
	case 134:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewDurationLabelFilter(log.LabelFilterNotEqual, syntaxDollar[1].str, syntaxDollar[3].dur)
		}
	case 135:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewDurationLabelFilter(log.LabelFilterEqual, syntaxDollar[1].str, syntaxDollar[3].dur)
		}
	case 136:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewDurationLabelFilter(log.LabelFilterEqual, syntaxDollar[1].str, syntaxDollar[3].dur)
		}
	case 137:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewBytesLabelFilter(log.LabelFilterGreaterThan, syntaxDollar[1].str, syntaxDollar[3].bytes)
		}
	case 138:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewBytesLabelFilter(log.LabelFilterGreaterThanOrEqual, syntaxDollar[1].str, syntaxDollar[3].bytes)
		}
	case 139:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewBytesLabelFilter(log.LabelFilterLesserThan, syntaxDollar[1].str, syntaxDollar[3].bytes)
		}
	case 140:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewBytesLabelFilter(log.LabelFilterLesserThanOrEqual, syntaxDollar[1].str, syntaxDollar[3].bytes)
		}
	case 141:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewBytesLabelFilter(log.LabelFilterNotEqual, syntaxDollar[1].str, syntaxDollar[3].bytes)
		}
	case 142:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewBytesLabelFilter(log.LabelFilterEqual, syntaxDollar[1].str, syntaxDollar[3].bytes)
		}
	case 143:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = log.NewBytesLabelFilter(log.LabelFilterEqual, syntaxDollar[1].str, syntaxDollar[3].bytes)
		}
	case 144:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = mustNewNumericLabelFilter(log.LabelFilterGreaterThan, syntaxDollar[1].str, syntaxDollar[3].literalExpr)
		}
	case 145:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = mustNewNumericLabelFilter(log.LabelFilterGreaterThanOrEqual, syntaxDollar[1].str, syntaxDollar[3].literalExpr)
		}
	case 146:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = mustNewNumericLabelFilter(log.LabelFilterLesserThan, syntaxDollar[1].str, syntaxDollar[3].literalExpr)
		}
	case 147:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = mustNewNumericLabelFilter(log.LabelFilterLesserThanOrEqual, syntaxDollar[1].str, syntaxDollar[3].literalExpr)
		}
	case 148:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = mustNewNumericLabelFilter(log.LabelFilterNotEqual, syntaxDollar[1].str, syntaxDollar[3].literalExpr)
		}
	case 149:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = mustNewNumericLabelFilter(log.LabelFilterEqual, syntaxDollar[1].str, syntaxDollar[3].literalExpr)
		}
	case 150:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.filterer = mustNewNumericLabelFilter(log.LabelFilterEqual, syntaxDollar[1].str, syntaxDollar[3].literalExpr)
		}
	case 151:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.namedMatcher = log.NewNamedLabelMatcher(nil, syntaxDollar[1].str)
		}
	case 152:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.namedMatcher = log.NewNamedLabelMatcher(syntaxDollar[1].matcher, "")
		}
	case 153:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.namedMatchers = []log.NamedLabelMatcher{syntaxDollar[1].namedMatcher}
		}
	case 154:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.namedMatchers = append(syntaxDollar[1].namedMatchers, syntaxDollar[3].namedMatcher)
		}
	case 155:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newDropLabelsExpr(syntaxDollar[2].namedMatchers)
		}
	case 156:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.stage = newKeepLabelsExpr(syntaxDollar[2].namedMatchers)
		}
	case 157:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("or", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 158:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("and", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 159:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("unless", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 160:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("+", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 161:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("-", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 162:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("*", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 163:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("/", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 164:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("%", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 165:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("^", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 166:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("==", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 167:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("!=", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 168:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr(">", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 169:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr(">=", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 170:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("<", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 171:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = mustNewBinOpExpr("<=", syntaxDollar[3].binOpts, syntaxDollar[1].expr, syntaxDollar[4].expr)
		}
	case 172:
		syntaxDollar = syntaxS[syntaxpt-0 : syntaxpt+1]
		{
			syntaxVAL.binOpts = &BinOpOptions{VectorMatching: &VectorMatching{Card: CardOneToOne}}
		}
	case 173:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.binOpts = &BinOpOptions{VectorMatching: &VectorMatching{Card: CardOneToOne}, ReturnBool: true}
		}
	case 174:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.On = true
			syntaxVAL.binOpts.VectorMatching.MatchingLabels = syntaxDollar[4].strs
		}
	case 175:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.On = true
		}
	case 176:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.MatchingLabels = syntaxDollar[4].strs
		}
	case 177:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
		}
	case 178:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
		}
	case 179:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
		}
	case 180:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.Card = CardManyToOne
		}
	case 181:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.Card = CardManyToOne
		}
	case 182:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.Card = CardManyToOne
			syntaxVAL.binOpts.VectorMatching.Include = syntaxDollar[4].strs
		}
	case 183:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.Card = CardOneToMany
		}
	case 184:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.Card = CardOneToMany
		}
	case 185:
		syntaxDollar = syntaxS[syntaxpt-5 : syntaxpt+1]
		{
			syntaxVAL.binOpts = syntaxDollar[1].binOpts
			syntaxVAL.binOpts.VectorMatching.Card = CardOneToMany
			syntaxVAL.binOpts.VectorMatching.Include = syntaxDollar[4].strs
		}
	case 186:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.literalExpr = mustNewLiteralExpr(syntaxDollar[1].str, false)
		}
	case 187:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.literalExpr = mustNewLiteralExpr(syntaxDollar[2].str, false)
		}
	case 188:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.literalExpr = mustNewLiteralExpr(syntaxDollar[2].str, true)
		}
	case 189:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.metricExpr = NewVectorExpr(syntaxDollar[3].str)
		}
	case 190:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.str = OpTypeVector
		}
	case 191:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeSum
		}
	case 192:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeAvg
		}
	case 193:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeCount
		}
	case 194:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeMax
		}
	case 195:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeMin
		}
	case 196:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeStddev
		}
	case 197:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeStdvar
		}
	case 198:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeBottomK
		}
	case 199:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeTopK
		}
	case 200:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeSort
		}
	case 201:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeSortDesc
		}
	case 202:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpTypeApproxTopK
		}
	case 203:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeCount
		}
	case 204:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeRate
		}
	case 205:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeRateCounter
		}
	case 206:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeBytes
		}
	case 207:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeBytesRate
		}
	case 208:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeAvg
		}
	case 209:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeSum
		}
	case 210:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeMin
		}
	case 211:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeMax
		}
	case 212:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeStdvar
		}
	case 213:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeStddev
		}
	case 214:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeQuantile
		}
	case 215:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeFirst
		}
	case 216:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeLast
		}
	case 217:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeAbsent
		}
	case 218:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeQuantileSketch
		}
	case 219:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeFirstWithTimestamp
		}
	case 220:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.op = OpRangeTypeLastWithTimestamp
		}
	case 221:
		syntaxDollar = syntaxS[syntaxpt-2 : syntaxpt+1]
		{
			syntaxVAL.offsetExpr = newOffsetExpr(syntaxDollar[2].dur)
		}
	case 222:
		syntaxDollar = syntaxS[syntaxpt-1 : syntaxpt+1]
		{
			syntaxVAL.strs = []string{syntaxDollar[1].str}
		}
	case 223:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.strs = append(syntaxDollar[1].strs, syntaxDollar[3].str)
		}
	case 224:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.grouping = &Grouping{Without: false, Groups: syntaxDollar[3].strs}
		}
	case 225:
		syntaxDollar = syntaxS[syntaxpt-4 : syntaxpt+1]
		{
			syntaxVAL.grouping = &Grouping{Without: true, Groups: syntaxDollar[3].strs}
		}
	case 226:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.grouping = &Grouping{Without: false, Groups: nil}
		}
	case 227:
		syntaxDollar = syntaxS[syntaxpt-3 : syntaxpt+1]
		{
			syntaxVAL.grouping = &Grouping{Without: true, Groups: nil}
		}
	}
	goto syntaxstack /* stack new state and value */
}
