// Code generated by wiresmith. DO NOT EDIT.
// source: pkg/util/httpgrpcpb/httpgrpcpb.proto

package httpgrpcpb

import (
	"github.com/grafana/wiresmith/protohelpers"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"reflect"
	"unsafe"
)

// Reflection / registration glue for pkg/util/httpgrpcpb/httpgrpcpb.proto.
//
// This file holds the per-message ProtoReflect() methods, the per-enum
// Descriptor()/Type()/Number() methods, the embedded FileDescriptorProto
// blob, the file_*_msgTypes / file_*_enumTypes arrays, and the init()
// that registers everything with protoregistry.GlobalFiles and
// protoregistry.GlobalTypes. None of these are called on the marshal /
// unmarshal / size hot path.
//
// Why a separate file? Putting this code (plus its descriptorpb /
// protoreflect / protoimpl imports — ~64KB of descriptorpb alone, ~377KB
// added to __TEXT overall) next to the hot Marshal/Unmarshal functions
// caused a measured +7–14% regression on otlp benchmarks (UnmarshalProfiles
// regressed by +12.6%) due to icache / iTLB / BTB pressure: the hot
// loops themselves were unchanged, but cold reflection code interleaved
// in the same compilation unit shifted hot functions onto different
// cache sets and pushed them ~131KB further into the binary. Emitting
// the cold half here, in its own .o, lets the linker place it away
// from the hot half and recovers that throughput.
//
// See compiler/generator/emit_registration.go for the full rationale
// and the benchmark methodology. DO NOT inline this file's contents
// back into the main .pb.go without re-measuring.

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	file_pkg_util_httpgrpcpb_httpgrpcpb_proto_init()
	return protohelpers.NewMessageReflect(&file_pkg_util_httpgrpcpb_httpgrpcpb_proto_msgTypes[0], x)
}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	file_pkg_util_httpgrpcpb_httpgrpcpb_proto_init()
	return protohelpers.NewMessageReflect(&file_pkg_util_httpgrpcpb_httpgrpcpb_proto_msgTypes[1], x)
}

func (x *Header) ProtoReflect() protoreflect.Message {
	file_pkg_util_httpgrpcpb_httpgrpcpb_proto_init()
	return protohelpers.NewMessageReflect(&file_pkg_util_httpgrpcpb_httpgrpcpb_proto_msgTypes[2], x)
}

const file_pkg_util_httpgrpcpb_httpgrpcpb_proto_rawDesc = "" +
	"\x0a\x24\x70\x6b\x67\x2f\x75\x74\x69\x6c\x2f\x68\x74\x74\x70\x67\x72\x70\x63\x70\x62\x2f\x68\x74\x74\x70\x67\x72\x70\x63\x70\x62\x2e\x70\x72\x6f\x74\x6f\x12\x0f" +
	"\x6c\x6f\x6b\x69\x2e\x68\x74\x74\x70\x67\x72\x70\x63\x70\x62\x22\x84\x01\x0a\x0b\x48\x54\x54\x50\x52\x65\x71\x75\x65\x73\x74\x12\x16\x0a\x06\x6d\x65\x74\x68\x6f" +
	"\x64\x18\x01\x20\x01\x28\x09\x52\x06\x6d\x65\x74\x68\x6f\x64\x12\x10\x0a\x03\x75\x72\x6c\x18\x02\x20\x01\x28\x09\x52\x03\x75\x72\x6c\x12\x37\x0a\x07\x68\x65\x61" +
	"\x64\x65\x72\x73\x18\x03\x20\x03\x28\x0b\x32\x17\x2e\x6c\x6f\x6b\x69\x2e\x68\x74\x74\x70\x67\x72\x70\x63\x70\x62\x2e\x48\x65\x61\x64\x65\x72\x42\x04\xf0\xb6\x18" +
	"\x01\x52\x07\x68\x65\x61\x64\x65\x72\x73\x12\x12\x0a\x04\x62\x6f\x64\x79\x18\x04\x20\x01\x28\x0c\x52\x04\x62\x6f\x64\x79\x22\x6f\x0a\x0c\x48\x54\x54\x50\x52\x65" +
	"\x73\x70\x6f\x6e\x73\x65\x12\x12\x0a\x04\x43\x6f\x64\x65\x18\x01\x20\x01\x28\x05\x52\x04\x43\x6f\x64\x65\x12\x37\x0a\x07\x68\x65\x61\x64\x65\x72\x73\x18\x02\x20" +
	"\x03\x28\x0b\x32\x17\x2e\x6c\x6f\x6b\x69\x2e\x68\x74\x74\x70\x67\x72\x70\x63\x70\x62\x2e\x48\x65\x61\x64\x65\x72\x42\x04\xf0\xb6\x18\x01\x52\x07\x68\x65\x61\x64" +
	"\x65\x72\x73\x12\x12\x0a\x04\x62\x6f\x64\x79\x18\x03\x20\x01\x28\x0c\x52\x04\x62\x6f\x64\x79\x22\x32\x0a\x06\x48\x65\x61\x64\x65\x72\x12\x10\x0a\x03\x6b\x65\x79" +
	"\x18\x01\x20\x01\x28\x09\x52\x03\x6b\x65\x79\x12\x16\x0a\x06\x76\x61\x6c\x75\x65\x73\x18\x02\x20\x03\x28\x09\x52\x06\x76\x61\x6c\x75\x65\x73\x42\x34\xc8\xb7\x18" +
	"\x01\x5a\x2e\x67\x69\x74\x68\x75\x62\x2e\x63\x6f\x6d\x2f\x67\x72\x61\x66\x61\x6e\x61\x2f\x6c\x6f\x6b\x69\x2f\x76\x33\x2f\x70\x6b\x67\x2f\x75\x74\x69\x6c\x2f\x68" +
	"\x74\x74\x70\x67\x72\x70\x63\x70\x62\x62\x06\x70\x72\x6f\x74\x6f\x33"

var file_pkg_util_httpgrpcpb_httpgrpcpb_proto_fd protoreflect.FileDescriptor

var file_pkg_util_httpgrpcpb_httpgrpcpb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)

var file_pkg_util_httpgrpcpb_httpgrpcpb_proto_goTypes = []any{
	(*HTTPRequest)(nil),  // 0: loki.httpgrpcpb.HTTPRequest
	(*HTTPResponse)(nil), // 1: loki.httpgrpcpb.HTTPResponse
	(*Header)(nil),       // 2: loki.httpgrpcpb.Header
}

var file_pkg_util_httpgrpcpb_httpgrpcpb_proto_depIdxs = []int32{
	2, // 0: loki.httpgrpcpb.HTTPRequest.headers:type_name -> loki.httpgrpcpb.Header
	2, // 1: loki.httpgrpcpb.HTTPResponse.headers:type_name -> loki.httpgrpcpb.Header
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_util_httpgrpcpb_httpgrpcpb_proto_init() }

func file_pkg_util_httpgrpcpb_httpgrpcpb_proto_init() {
	if file_pkg_util_httpgrpcpb_httpgrpcpb_proto_fd != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_util_httpgrpcpb_httpgrpcpb_proto_rawDesc), len(file_pkg_util_httpgrpcpb_httpgrpcpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_util_httpgrpcpb_httpgrpcpb_proto_goTypes,
		DependencyIndexes: file_pkg_util_httpgrpcpb_httpgrpcpb_proto_depIdxs,
		MessageInfos:      file_pkg_util_httpgrpcpb_httpgrpcpb_proto_msgTypes,
	}.Build()
	file_pkg_util_httpgrpcpb_httpgrpcpb_proto_fd = out.File
	file_pkg_util_httpgrpcpb_httpgrpcpb_proto_goTypes = nil
	file_pkg_util_httpgrpcpb_httpgrpcpb_proto_depIdxs = nil
}
