// Code generated by wiresmith. DO NOT EDIT.
// source: pkg/util/httpgrpcpb/httpgrpcpb.proto

package httpgrpcpb

import (
	"bytes"
)

// Per-message value-comparison methods (Equal + Compare) for pkg/util/httpgrpcpb/httpgrpcpb.proto.
//
// Equal returns bool; Compare returns -1/0/+1 like bytes.Compare with the
// gogoproto.compare nil/wrong-type preamble. Both are emitted on every
// message; callers that don't use one can rely on Go's dead-code
// elimination to drop the body.
//
// Why a separate file? Equal/Compare are never called from Marshal/Unmarshal/
// Size, but emitting them next to those hot functions in the main .pb.go
// pushed them onto different cache sets and produced a measured ~9% geomean
// regression on OTel benchmarks (UnmarshalMap +14%, MarshalSingleSpan +13%)
// purely from icache / iTLB / BTB pressure. Splitting them into their own
// compilation unit gives the linker freedom to place the cold half away
// from the hot half — same trick the _util.pb.go split uses.
//
// See compiler/generator/emit_compare.go / emit_equal.go for the full
// rationale and the benchmark methodology. DO NOT inline this file's
// contents back into the main .pb.go without re-measuring.

func (this *HTTPRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HTTPRequest)
	if !ok {
		that2, ok := that.(HTTPRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Method != that1.Method {
		return false
	}
	if this.Url != that1.Url {
		return false
	}
	if len(this.Headers) != len(that1.Headers) {
		return false
	}
	for i := range this.Headers {
		if (this.Headers[i] == nil) != (that1.Headers[i] == nil) {
			return false
		}
		if this.Headers[i] != nil && !this.Headers[i].Equal(that1.Headers[i]) {
			return false
		}
	}
	if !bytes.Equal(this.Body, that1.Body) {
		return false
	}
	return true
}

func (this *HTTPResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HTTPResponse)
	if !ok {
		that2, ok := that.(HTTPResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if len(this.Headers) != len(that1.Headers) {
		return false
	}
	for i := range this.Headers {
		if (this.Headers[i] == nil) != (that1.Headers[i] == nil) {
			return false
		}
		if this.Headers[i] != nil && !this.Headers[i].Equal(that1.Headers[i]) {
			return false
		}
	}
	if !bytes.Equal(this.Body, that1.Body) {
		return false
	}
	return true
}

func (this *Header) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Header)
	if !ok {
		that2, ok := that.(Header)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Key != that1.Key {
		return false
	}
	if len(this.Values) != len(that1.Values) {
		return false
	}
	for i := range this.Values {
		if this.Values[i] != that1.Values[i] {
			return false
		}
	}
	return true
}

func (this *HTTPRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*HTTPRequest)
	if !ok {
		that2, ok := that.(HTTPRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Method != that1.Method {
		if this.Method < that1.Method {
			return -1
		}
		return 1
	}
	if this.Url != that1.Url {
		if this.Url < that1.Url {
			return -1
		}
		return 1
	}
	if len(this.Headers) != len(that1.Headers) {
		if len(this.Headers) < len(that1.Headers) {
			return -1
		}
		return 1
	}
	for i := range this.Headers {
		if (this.Headers[i] == nil) != (that1.Headers[i] == nil) {
			if this.Headers[i] == nil {
				return -1
			}
			return 1
		}
		if this.Headers[i] != nil {
			if c := this.Headers[i].Compare(that1.Headers[i]); c != 0 {
				return c
			}
		}
	}
	if c := bytes.Compare(this.Body, that1.Body); c != 0 {
		return c
	}
	return 0
}

func (this *HTTPResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*HTTPResponse)
	if !ok {
		that2, ok := that.(HTTPResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Code != that1.Code {
		if this.Code < that1.Code {
			return -1
		}
		return 1
	}
	if len(this.Headers) != len(that1.Headers) {
		if len(this.Headers) < len(that1.Headers) {
			return -1
		}
		return 1
	}
	for i := range this.Headers {
		if (this.Headers[i] == nil) != (that1.Headers[i] == nil) {
			if this.Headers[i] == nil {
				return -1
			}
			return 1
		}
		if this.Headers[i] != nil {
			if c := this.Headers[i].Compare(that1.Headers[i]); c != 0 {
				return c
			}
		}
	}
	if c := bytes.Compare(this.Body, that1.Body); c != 0 {
		return c
	}
	return 0
}

func (this *Header) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Header)
	if !ok {
		that2, ok := that.(Header)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Key != that1.Key {
		if this.Key < that1.Key {
			return -1
		}
		return 1
	}
	if len(this.Values) != len(that1.Values) {
		if len(this.Values) < len(that1.Values) {
			return -1
		}
		return 1
	}
	for i := range this.Values {
		if this.Values[i] != that1.Values[i] {
			if this.Values[i] < that1.Values[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}
