apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      volumes:
      - name: loki-operator-metrics-cert
        secret:
          defaultMode: 420
          optional: true
          secretName: loki-operator-metrics
      securityContext:
        runAsNonRoot: true
