<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>treetop</string>
		<string>tt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(module|grammer|rule).*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*end</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Treetop Grammar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(module) ([A-Z]\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.begin.module.treetop</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.module.treetop</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\1(end)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.end.module.treetop</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.treetop</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(grammar) ([A-Z]\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.begin.grammar.treetop</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.grammar.treetop</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\1(end)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.end.grammar.treetop</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.grammar.treetop</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.include.treetop</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.include.treetop</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(include)\s+(\w+)</string>
			<key>name</key>
			<string>meta.include.treetop</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(rule)\b (\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.begin.rule.treetop</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.rule.treetop</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s+\bend\b\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.end.rule.treetop</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule.treetop</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#character-class</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\/</string>
					<key>name</key>
					<string>keyword.operator.or.treetop</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;\w+?&gt;</string>
					<key>name</key>
					<string>variable.class-instance.treetop</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+?:</string>
					<key>name</key>
					<string>support.operand.treetop</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.embedded-ruby.treetop</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>character-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[wWsSdDhH]|\.</string>
					<key>name</key>
					<string>constant.character.character-class.regexp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.backslash.regexp</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)(\^)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.regexp</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.negation.regexp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.regexp</string>
						</dict>
					</dict>
					<key>name</key>
					<string>constant.other.character-class.set.regexp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#character-class</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape.backslash.regexp</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape.backslash.regexp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(.|(\\.))\-([^\]]|(\\.))</string>
							<key>name</key>
							<string>constant.other.character-class.range.regexp</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&amp;&amp;</string>
							<key>name</key>
							<string>keyword.operator.intersection.regexp</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.treetop</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.treetop</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.treetop</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.treetop</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.treetop</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(u\h{4}|.)</string>
							<key>name</key>
							<string>constant.character.escape.antlr</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.treetop</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.treetop</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.treetop</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.treetop</string>
	<key>uuid</key>
	<string>A1604A34-0B73-4D5A-9499-87D881DFA8D5</string>
</dict>
</plist>
