{
 "title": "Loki / Stream Sharding",
 "tags": [
  "loki",
  "loki-dashboards-as-code"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(loki_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "loki_datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Stream Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_rate_store_streams{namespace=~\"$namespace\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Sharding Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(loki_stream_sharding_count{namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Max Shards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_rate_store_max_stream_shards{namespace=~\"$namespace\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Shard Count Distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le)(rate(loki_rate_store_stream_shards_bucket{namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "p99 Refresh",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(loki_rate_store_refresh_duration_seconds_bucket{namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "p50 Refresh",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(loki_rate_store_refresh_duration_seconds_bucket{namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Stream Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_rate_store_max_stream_rate_bytes{namespace=~\"$namespace\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Max Unique",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_rate_store_max_unique_stream_rate_bytes{namespace=~\"$namespace\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(loki_rate_store_stream_rate_bytes_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}