apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack-sample
spec:
  size: 1x.small
  storage:
    schemas:
    - version: v13
      effectiveDate: "2024-01-01"
    secret:
      name: test
  storageClassName: standard
