[
  (import './base.libsonnet'),
  (import './config.libsonnet'),
  (import './labels.libsonnet'),
  (import './selectors.libsonnet'),
  (import './components/admin-api.libsonnet'),
  (import './components/bloom-builder.libsonnet'),
  (import './components/bloom-gateway.libsonnet'),
  (import './components/bloom-planner.libsonnet'),
  (import './components/compactor.libsonnet'),
  (import './components/cortex-gateway.libsonnet'),
  (import './components/distributor.libsonnet'),
  (import './components/gateway.libsonnet'),
  (import './components/index-gateway.libsonnet'),
  (import './components/ingester.libsonnet'),
  (import './components/ingester-zone.libsonnet'),
  (import './components/overrides-exporter.libsonnet'),
  (import './components/partition-ingester.libsonnet'),
  (import './components/pattern-ingester.libsonnet'),
  (import './components/querier.libsonnet'),
  (import './components/query-frontend.libsonnet'),
  (import './components/query-scheduler.libsonnet'),
  (import './components/ruler.libsonnet'),
]
