#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

BRANCH=$(git rev-parse --abbrev-ref HEAD)
SHA=$(git rev-parse --short HEAD)

# If this is a tag, use it,                otherwise branch-hash
git describe --exact-match 2> /dev/null || echo "${BRANCH}-${SHA}"
