#!/usr/bin/env bash
ghr \
  -t "${GITHUB_TOKEN}" \
  -u "${DRONE_REPO_OWNER}" \
  -r "${DRONE_REPO_NAME}" \
  -c "${DRONE_COMMIT}" \
  -b="$(cat ./tools/release-note.md | envsubst)" \
  -delete -draft \
  "${DRONE_TAG}" ./dist/
