#!/usr/bin/env bash
ghr \
  -t "${GITHUB_TOKEN}" \
  -u "${CIRCLE_USERNAME}" \
  -r "${CIRCLE_PROJECT_REPONAME}" \
  -c "${CIRCLE_SHA1}" \
  -b="$(cat ./tools/release-note.md | envsubst)" \
  -delete -draft \
  "test-v1.2.0" ./dist/
