#!/usr/bin/env bash
ghr \
  -t "${GITHUB_TOKEN}" \
  -u "${CIRCLE_PROJECT_USERNAME}" \
  -r "${CIRCLE_PROJECT_REPONAME}" \
  -c "${CIRCLE_SHA1}" \
  -b="$(cat ./tools/release-note.md | envsubst)" \
  -delete -draft \
  "${CIRCLE_TAG}" ./dist/
