"jobs":
  "check":
    "uses": "grafana/loki-release/.github/workflows/check.yml@3ad7fe2245c48b63eb8887fcc6dd7bcc08f9bff6"
    "with":
      "build_image": "grafana/loki-build-image:0.35.1"
      "golang_ci_lint_version": "v2.10.1"
      "release_lib_ref": "3ad7fe2245c48b63eb8887fcc6dd7bcc08f9bff6"
      "skip_validation": false
      "use_github_app_token": true
"name": "check"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"
"permissions":
  "contents": "read"
  "pull-requests": "read"