"jobs":
  "check":
    "uses": "grafana/loki-release/.github/workflows/check.yml@ab3eb3e72e185daa72c9a70c589bde074faaf0dc"
    "with":
      "build_image": "golang:1.26.4"
      "golang_ci_lint_version": "v2.10.1"
      "release_lib_ref": "ab3eb3e72e185daa72c9a70c589bde074faaf0dc"
      "skip_validation": false
      "use_github_app_token": true
"name": "check"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"
"permissions":
  "contents": "read"
  "pull-requests": "read"