name: Clean up orphaned branches
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  cleanup-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/shared-workflows/actions/cleanup-branches@cleanup-branches/v0.2.1
        with:
          dry-run: "true"

