# Auto-merge as documented in official Github docs
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

name: Auto-review Dependabot PRs
on: pull_request

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  dependabot-reviewer:
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v 2.3.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@580590a644e82e79bb2598bdaba0be245a14dda0 # create-github-app-token/v0.2.2
        with:
          github_app: loki-gh-app

      - name: Approve and auto-merge the dependabot PR
        run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr review $PR_URL \
          --approve -b "Auto approve dependencies bump PR"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
