name: Helm tagged release PR

on:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  weekly-release-pr:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name || 'test' }}"
      BUILD_IN_CONTAINER: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="v1.11.2"
          curl -fsSL "https://github.com/norwoodj/helm-docs/releases/download/${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION#v}_Linux_x86_64.tar.gz" \
            | tar -xzf - -C "$RUNNER_TEMP" helm-docs
          echo "$RUNNER_TEMP" >> "$GITHUB_PATH"

      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        with:
          github_app: loki-gh-app

      - name: Update/regenerate files
        id: update
        run: |
          bash .github/workflows/scripts/helm-tagged-release.sh ${RELEASE_VERSION}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore: release loki helm chart ${{ steps.update.outputs.new_chart_version }}"
          body: Automated PR created by [helm-tagged-release-pr.yaml](https://github.com/grafana/loki/blob/main/.github/workflows/helm-tagged-release-pr.yaml)
          commit-message: Update loki chart to ${{ steps.update.outputs.new_chart_version }}
          branch: helm-chart-tagged-${{ steps.update.outputs.new_chart_version }}
          base: main
          labels: helm
