name: Helm weekly release PR

on:
  schedule:
    - cron: '0 10 * * 2' # 10 UTC every Tuesday (since ks get cut on Monday)

permissions:
  contents: "read"
  id-token: "write"
  pull-requests: "write"

jobs:
  weekly-release-pr:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    env:
      BUILD_IN_CONTAINER: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="v1.11.2"
          curl -fsSL "https://github.com/norwoodj/helm-docs/releases/download/${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION#v}_Linux_x86_64.tar.gz" \
            | tar -xzf - -C "$RUNNER_TEMP" helm-docs
          echo "$RUNNER_TEMP" >> "$GITHUB_PATH"
      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@46f48da11e78ebdba7a8747ae456b11062fac83e # create-github-app-token/v0.3.1
        with:
          github_app: loki-gh-app

      - name: "Login to DockerHub (from vault)"
        uses: "grafana/shared-workflows/actions/dockerhub-login@75804962c1ba608148988c1e2dc35fbb0ee21746"

      - name: Update/regenerate files for standard release
        id: update
        run: |
          bash .github/workflows/scripts/helm-weekly-release.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore: release loki helm chart ${{ steps.update.outputs.new_chart_version }}"
          body: Automated PR created by [helm-weekly-release-pr.yaml](https://github.com/grafana/loki/blob/main/.github/workflows/helm-weekly-release-pr.yaml)
          commit-message: Update loki chart to ${{ steps.update.outputs.new_chart_version }}
          branch: helm-chart-weekly-${{ steps.update.outputs.new_chart_version }}
          base: main
          labels: helm
