name: Helm tagged release PR

on:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  weekly-release-pr:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name || 'test' }}"
      BUILD_IN_CONTAINER: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="v1.11.2"
          curl -fsSL "https://github.com/norwoodj/helm-docs/releases/download/${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION#v}_Linux_x86_64.tar.gz" \
            | tar -xzf - -C "$RUNNER_TEMP" helm-docs
          echo "$RUNNER_TEMP" >> "$GITHUB_PATH"

      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@ae92934a14a48b94494dbc06d74a81d47fe08a40 # create-github-app-token/v0.2.2
        with:
          github_app: loki-gh-app

      - name: Update/regenerate files
        id: update
        run: |
          bash .github/workflows/scripts/helm-tagged-release.sh ${RELEASE_VERSION}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore: release loki helm chart ${{ steps.update.outputs.new_chart_version }}"
          body: Automated PR created by [helm-tagged-release-pr.yaml](https://github.com/grafana/loki/blob/main/.github/workflows/helm-tagged-release-pr.yaml)
          commit-message: Update loki chart to ${{ steps.update.outputs.new_chart_version }}
          branch: helm-chart-tagged-${{ steps.update.outputs.new_chart_version }}
          base: main
          labels: helm
