name: "Pull Request Labeler"
on:
- pull_request

permissions:
  contents: read

jobs:
  triage:
    # We don't run the triaging for PRs from forks because those can't use the loki-gh-app token broker.
    # We don't use GitHub actions app (secrets.GITHUB_TOKEN) because PRs created by the bot don't trigger CI.
    if: ${{ ! github.event.pull_request.head.repo.fork }}

    runs-on: ubuntu-x64-small
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
    - name: Generate GitHub App Token
      id: app-token
      uses: grafana/shared-workflows/actions/create-github-app-token@580590a644e82e79bb2598bdaba0be245a14dda0 # create-github-app-token/v0.2.2
      with:
        github_app: loki-gh-app

    - uses: actions/labeler@v5
      with:
        repo-token: "${{ steps.app-token.outputs.token }}"
