---
name: "Lint And Build Nix Flake"
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "go.mod"
      - "nix/**"
      - .github/workflows/nix-ci.yaml

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix run --print-build-logs .#lint
  packages:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build --print-build-logs .#logcli
      - run: nix build --print-build-logs .#loki
      - run: nix build --print-build-logs .#loki-canary
