---
name: "Lint And Build Nix Flake"
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "go.mod"
      - "nix/**"
      - .github/workflows/nix-ci.yaml

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix run --print-build-logs .#lint
  packages:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build --print-build-logs .#logcli
      - run: nix build --print-build-logs .#loki
      - run: nix build --print-build-logs .#loki-canary
