name: operator-release-please

on:
  push:
    paths:
      - 'operator/**'
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  releasePlease:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    outputs:
      release_created: ${{ steps.release.outputs.operator--release_created }}
      release_name: ${{ steps.release.outputs.operator--tag_name }}
      release_major: ${{ steps.release.outputs.operator--major }}
      release_minor: ${{ steps.release.outputs.operator--minor }}
      release_patch: ${{ steps.release.outputs.operator--patch }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@ae92934a14a48b94494dbc06d74a81d47fe08a40 # create-github-app-token/v0.2.2
        with:
          github_app: loki-gh-app

      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          path: operator
          config-file: operator/release-please-config.json
          token: ${{ steps.app-token.outputs.token }}
  publishImages:
    needs:
      - "releasePlease"
    if: ${{ needs.releasePlease.outputs.release_created }}
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/operator-reusable-image-build.yml
    with:
      dockerfile: "operator/Dockerfile"
      registry: "us-docker.pkg.dev"
      organization: "grafanalabs-global/dockerhub-loki-prod-mirror"
      image_name: "loki-operator"
      tag: ${{ needs.releasePlease.outputs.release_major }}.${{ needs.releasePlease.outputs.release_minor }}.${{ needs.releasePlease.outputs.release_patch }}
  publishRelease:
    needs:
    - "releasePlease"
    - "publishImages"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    if: ${{ needs.releasePlease.outputs.release_created }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@ae92934a14a48b94494dbc06d74a81d47fe08a40 # create-github-app-token/v0.2.2
        with:
          github_app: loki-gh-app
      - name: "pull code to release"
        uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # v6.0.3
        with:
          persist-credentials: false
          path: "release"
      - name: "publish release"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          RELEASE_NAME: ${{ needs.releasePlease.outputs.release_name }}
        working-directory: "release"
        run: |
          gh release edit "$RELEASE_NAME" --draft=false --latest=false
