name: operator bundle

on:
  push:
    paths:
      - 'operator/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'operator/**'

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false
    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version-file: ./operator/go.mod
        cache-dependency-path: ./operator/go.sum
    - name: make bundle
      run: |
        make bundle-all && git diff --exit-code -I'^    createdAt: '
      working-directory: ./operator
