name: publish-technical-documentation-next

on:
  push:
    branches:
      - main
    paths:
      - "docs/sources/**"

permissions:
  contents: read

jobs:
  sync:
    if: github.repository == 'grafana/loki'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-x64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: grafana/writers-toolkit/publish-technical-documentation@publish-technical-documentation/v1
        with:
          website_directory: content/docs/loki/next
