name: Relyance Compliance Inspection
on:
  schedule:
    - cron: '0 0 * * *' # Run daily at 00:00 UTC
  workflow_dispatch: # Allow for manual trigger

permissions:
  contents: read

jobs:
  relyance:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-x64
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          'persist-credentials': false

      - name: retrieve secrets
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@7d18a46aafb8b875ed76a0bc98852d74b91e7f91 # v1.0.0
        with:
          repo_secrets: |
            RELYANCE_API_KEY=relyance:API_KEY

      - name: Run Relyance Compliance Inspector
        run: |
          docker pull gcr.io/relyance-ext/compliance_inspector:release && \
          docker run --rm -v `pwd`:/repo --env "API_KEY=${{ env.RELYANCE_API_KEY }}" gcr.io/relyance-ext/compliance_inspector:release 
