name: TruffleHog Secrets Scan
on: [pull_request]

permissions:
  contents: read

jobs:
  TruffleHog:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # v3.95.9
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
