name: TruffleHog Secrets Scan
on: [pull_request]

permissions:
  contents: read

jobs:
  TruffleHog:
    runs-on: ubuntu-x64
    permissions:
      contents: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@37b77001d0174ebec2fcca2bd83ff83a6d45a3ab # v3.95.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
