name: syft-sbom-ci

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  syft-sbom:

    runs-on: ubuntu-x64
    permissions:
      actions: read
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Anchore SBOM Action
      uses: anchore/sbom-action@aa80c8c5bd439a416a62804f2151ab38c671a638 # v0.24.1
      with:
         artifact-name: ${{ github.event.repository.name }}-spdx.json
