name: syft-sbom-ci

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  syft-sbom:

    runs-on: ubuntu-x64
    permissions:
      actions: read
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Anchore SBOM Action
      uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
      with:
         artifact-name: ${{ github.event.repository.name }}-spdx.json
