source 'https://rubygems.org'

gemspec

logstash_path = ENV["LOGSTASH_PATH"] || "./logstash"

if Dir.exist?(logstash_path)
  gem 'logstash-core', :path => "#{logstash_path}/logstash-core"
  gem 'logstash-core-plugin-api', :path => "#{logstash_path}/logstash-core-plugin-api"
else
  raise 'missing logstash vendoring'
end

gem "webmock", "~> 3.8"
# I could not find the reason why the `cgi` gem is required after the upgrade of jruby inside the logstash bash Docker image.
# However, the build fails without this dependency.
gem "cgi"
